### ISSUE TITLE
Add game instructions wireframe

### ISSUE THREAD

**Issue by Joaquin939** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#104]
Description

This task consists of adding a wireframe for the game instructions. 

Reason:

It is a basic element every game must have for the new players who don't understand the rules of the game.

Current Task Objective:

This issue will focus on building the wireframe, with another issue having to do with creating the visual elements.

Design Link:
https://www.figma.com/design/9tB7x524EnEF8I57CyxoMg/Colors%2C-Defaults%2C-Screens?node-id=0-1&node-type=canvas&t=axwxo9Dh0D6QoUut-0

Priority: 5
Difficulty: 3

**Comment by PinkSylvie** [comment]
Hello! I looked at the wireframe and I was a bit concerned that the design and palette doesn’t seem to follow the direction the mock up and the rest of the assets are heading towards which is a retro pixel art style with the color palette sent in the team chat. Some suggestions:
- For the font maybe a readable pixel font like [Peepo Regular](https://www.urbanfonts.com/fonts/pixel-fonts.htm)?
- For the font color maybe a dark brown like, #582400
- For the rules background maybe a light yellow like  #FFFEC9

-  ![Image](https://github.com/user-attachments/assets/7ff4f2d2-b2ef-4635-963b-aa7fc8fec93e)
![Image](https://github.com/user-attachments/assets/ae135125-31d0-4f85-ba67-5fc5e4cc279a)
![Image](https://github.com/user-attachments/assets/ede3993a-0423-4d11-b35e-0b8feebb016b)

**Comment by Joaquin939** [comment]
> Hello! I looked at the wireframe and I was a bit concerned that the design and palette doesn’t seem to follow the direction the mock up and the rest of the assets are heading towards which is a retro pixel art style with the color palette sent in the team chat. Some suggestions:
> 
> * For the font maybe a readable pixel font like [Peepo Regular](https://www.urbanfonts.com/fonts/pixel-fonts.htm)?
> * For the font color maybe a dark brown like, #582400
> * For the rules background maybe a light yellow like  #FFFEC9
> * ![Image](https://github.com/user-attachments/assets/7ff4f2d2-b2ef-4635-963b-aa7fc8fec93e)
>   ![Image](https://github.com/user-attachments/assets/ae135125-31d0-4f85-ba67-5fc5e4cc279a)
>   ![Image](https://github.com/user-attachments/assets/ede3993a-0423-4d11-b35e-0b8feebb016b)

Thank you, I finished updating the color palette so that it matches the style of the game

**Comment by PinkSylvie** [comment]
It looks great! @AngelCIICMorales @Keiven-Soto what do you think? Will you be implementing this as well for task #105 ?

**Comment by AngelCIICMorales** [comment]
LGTM!
