### ISSUE TITLE
[Lecture Topic Task] Identify, define and add Aggregates to the Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#109]
This task is part of Milestone 2 Guidelines section of "Application of topics, techniques, tools, methods, … from the lectures", as such is it is a Lecture Topic Task. 

The task entails to add to the documentation document the aggregates as detailed in the guidelines and as discussed in class: 

    The team identifies and defines at least one aggregate consisting of
    multiple objects with one aggregate root. The aggregate captures a
    conceptual whole and the objects inside the aggregate boundary make
    sense as separate concepts on the one hand while justifiably
    belonging inside the aggregate boundary. The team uses the aggregate
    correctly: e.g. all access to inner objects is through the root
    object, the functions on the root object ensure the invariants,…"

Score:
Urgency: 4
Difficulty: 2

**Comment by PinkSylvie** [comment]
After discussions with the gamestate team lead and feedback from the professor, I added a new section to the documentation that includes the aggregates and invariants as discussed in class. This section is section 4.3 Please review @AngelCIICMorales @Keiven-Soto

**Comment by PinkSylvie** [comment]
@Angel could you please close this task as well? It was the other half of the one you already closed

**Comment by AngelCIICMorales** [comment]
LGTM
