### ISSUE TITLE
[Lecture Topic Task] Add Aggregate Invariants to the Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#110]
This task is part of Milestone 2 Guidelines section of "Application of topics, techniques, tools, methods, … from the lectures", as such is it is a Lecture Topic Task.

The task entails to add to the documentation document the aggregate invariants as detailed in the guidelines and as discussed in class:

    The team states at least one non-trivial invariant of an aggregate.
    They state where the invariant might be violated temporarily and
    where it will be reestablished.

Score:
Urgency: 4
Difficulty: 2

**Comment by AngelCIICMorales** [comment]
LGTM
