### ISSUE TITLE
[Lecture Topic Task] Add Repositories to the documentation

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#122]
The team uses repositories to expose an interface providing persistence related functions in terms of the domain and/or the application layer.

Temporary Points:
Urgency: 4
Difficulty: 2

**Comment by JadiellMV** [comment]
This should take care of this task, please reach out if something needs to be changed or added!

The team uses repositories to take care of the logic that interacts with the database and at the same time separates persistence concerns from the domain and application layers. Each repository provides functions specific to their domain model. The structure used in the project improves maintainability, scalability, and testability by allowing changes without affecting the higher layers of the application.
The repositories in this project handle key entities like users and game rooms, each one belonging to its own repository. By following a consistent CRUD (Create, Read, Update, Delete) pattern, these repositories provide an efficient way to manage data while making sure that all domain-specific rules are handled correctly.
Below are descriptions of the main repositories, each managing its respective entity and interacting with MongoDB through Mongoose models:
UserRepository (UserHandler):
Handles user creation, authentication, and management. This repository interacts with the UserModel and allows to do operations such as user creation, email lookup, username lookup, password validation, and JWT token generation through the use of specific functions for each of these. These functions are essential for managing player accounts, ensuring secure login processes, and allowing smooth password recovery workflows. The specific functions that pertain to this repository are getAllUsers, that returns a list containing every user in the database, createUser, that creates and stores in the database a new user with the username, email, password, and unique uuid, findUserByEmail and findUserByUsername both look if the parameter given exists within the database, logoutUser makes sure that the logout is done correctly of the user given, validatePassword is used in the login and compares if the password entered matches the one stored in the database, generateToken generates and assigns a token to the given user,  and verifyToken, that  verifies if the token given is valid and has not expired.
RoomRepository (RoomsController):
Handles the creation and control of game rooms through the RoomModel. It provides functionality to create new rooms, check for the existence of a room by its identifier, and manage the players associated with each room. This repository is of great importance when it comes to handling online lobbies and facilitating multiplayer interactions. The functions inside this repository are getAllRooms, that retrieve all the rooms in the database, createRoom first checks if all the conditions are in place (like unique ids) before creating a new room, and joinRoom, that allows users to join an existing room while making sure that the user and the room exists and that the max capacity has not yet been met.

**Comment by ebrain-mendoza121** [comment]
Looks good!

**Comment by PinkSylvie** [comment]
@AngelCIICMorales @Keiven-Soto

**Comment by AngelCIICMorales** [comment]
LGTM
