### ISSUE TITLE
[UI Team] Create mock up / visual assets for multiplayer leaderboard

### ISSUE THREAD

**Issue by DavidCuevas3** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#125]
Create a basic mock up to illustrate how the multiplayer leaderboard could look like matching the already predetermined color pallet and style of the game.

Figma Link:
https://www.figma.com/design/9tB7x524EnEF8I57CyxoMg/Colors%2C-Defaults%2C-Screens?node-id=0-1&t=n33iHJ7yqmC4uZWJ-1

**Comment by DavidCuevas3** [comment]
### Mockup
The eventual implementation will have a more detailed look, but the mockup illustrates the wooden board style of leaderboard, simulating a wooden domino table

![image](https://github.com/user-attachments/assets/fd920733-7a51-442c-aee5-ee02929e9fa5)

**Comment by AngelCIICMorales** [comment]
I Love it!
