### ISSUE TITLE
[Lecture Topic Task] M3: Add Assertions to the documentation 

### ISSUE THREAD

**Issue by sandy-marrero** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#132]
> The team shows assertions from their project. For example, they show a
> pre-condition and a post-condition for one of their commands.

Description taken from the Milestone 3 guidelines.

Urgency: 4
Difficulty: 1

**Comment by sandy-marrero** [comment]
Assertions shown using the placeDomino function, including preconditions, postconditions.

[Link](https://docs.google.com/document/d/1b9jq6jZSDqksRkCoznBvjo1JBjC3aZ1K8VhusiSQAag/edit?usp=sharing)

**Comment by AngelCIICMorales** [comment]
LGTM

**Comment by sandy-marrero** [comment]
This falls in the case of LTT task that is part of the required/graded components of the documentation for Milestone 3, task score should not be 1 following what was said in the group during Saturday. @AngelCIICMorales @Keiven-Soto

**Comment by Keiven-Soto** [comment]
LTT was created on last milestone.  LTT is required in the documentation. Therefor score will be changed to urgency 2 and difficulty 2
