### ISSUE TITLE
[Lecture Topic Task] M3: Add intention revealing interfaces to the documentation.

### ISSUE THREAD

**Issue by sandy-marrero** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#134]
> The team shows examples where they originally had an interface that
> was not very intention revealing and then they worked toward making it
> more intention revealing.

Description taken from the Milestone 3 guidelines. 

Urgency: 4
Difficulty: 2

**Comment by AngelCIICMorales** [comment]
LGTM
