### ISSUE TITLE
Board Palette Adaptation and Changes 🎲

### ISSUE THREAD

**Issue by frances-sepulveda** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#137]
The board will be implemented for the game matching the palettes. Utilizing the feedback from M1, we will replace some of the boards that were made in order to have more coherency and aesthetics on the board so that it can be implemented by the Gamestate Team accordingly. 

The idea is to create at least 3 new domino boards that are according to the designated palette and that are visually stimulating but also simplistic to avoid oversaturating the screen with extra features. Once approved this will be added to the Project Shared Folder.

Scoring
Urgency: 4
Difficulty: 4

**Comment by rukitoyordan** [comment]
![MultiplayerDomino_Board](https://github.com/user-attachments/assets/f0ecd52f-86b4-4a73-8721-9a1edf1af724)
![PuertoRican_Board](https://github.com/user-attachments/assets/3a677faf-78f8-416e-87ea-5f3195ef9658)
![TwoDomino_Board](https://github.com/user-attachments/assets/ef0be073-ba0d-4561-8011-d00f4e88434c)

Please review the according boards and let us know if you need additional boards or features to be updated.

**Comment by AngelCIICMorales** [comment]
@PinkSylvie please give your take on these designs. I personally find the first one (the one with the M) to be a combination of too many bright colors. Maybe make its background similar to the third board.

**Comment by PinkSylvie** [comment]
I like how they look! Tho I understand that the game tiles could get lost on the first with such a bright color.

**Comment by AngelCIICMorales** [comment]
For now, they are all good. If the need arises, we can make some small alterations later.
