### ISSUE TITLE
Palette improvement 

### ISSUE THREAD

**Issue by frances-sepulveda** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#139]
This issue addresses inconsistencies in the visual appearance of the game board by standardizing the color palettes according with the rest visual designs. The update ensures that the game board design aligns with the predefined color schemes used throughout the game, providing a cohesive and visually appealing experience for players.

**Comment by frances-sepulveda** [comment]
The main board was changed to the following to match the game palette better.

![PHOTO-2024-10-09-15-27-49](https://github.com/user-attachments/assets/5470451c-b159-4ee7-8923-56f3d20e81c1)
![PHOTO-2024-10-09-15-24-55](https://github.com/user-attachments/assets/4dc23f7b-3104-4a7c-a5a5-cd0bdd5234c5)

**Comment by PinkSylvie** [comment]
I’m confused on what is the drawing on the first board

**Comment by PinkSylvie** [comment]
@AngelCIICMorales

**Comment by PinkSylvie** [comment]
@Keiven-Soto

**Comment by AngelCIICMorales** [comment]
LGTM

**Comment by rukitoyordan** [comment]
@PinkSylvie sorry for the late reply here. It is supposed to be like a fireball thing. Seeing that the palette had fire as a theme 🔥 I tried to make a spiraling fireball in the middle. Does this clarify your doubt?
