### ISSUE TITLE
[Lecture Topic Task] Refactor Persistence Layer leveraging the SOLID principles

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#145]
Currently, the models in the Persistence Layer are too thin. Forcing the user to create complex queries and spilling details in other layers (e.g. Controllers or Handlers). This task is to encapsulate the model where the definition of queries can exist and be defined. Creating more explicit methods when querying the database, simplifying other layers.

To complete this task, every model should be wrapped around another class that will interact directly with the defined model, closing the model for unnecessary use in other layers. Identify and justify the SOLID principle used to make the changes.

Proposed Score = Difficulty * Urgency = 3 * 3 = 9 pts

**Comment by AngelCIICMorales** [comment]
Please add the changes in the description.

**Comment by AngelCIICMorales** [comment]
Since the maximum score is 8 that is what you will recieve.
