### ISSUE TITLE
Draw Dominoes Game Mode

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#155]
Implement the Draw Dominoes game mode into the already existing Rule Engine. This task involves adopting the rule set specified here https://www.dominorules.com/draw for a 1v1 game and includes an onscreen score tracker so that the player knows when they're close to achieving victory for the game. Bugs involving the inability to grab random dominoes when there are still available dominoes and an audio issue were also fixed.

Priority 4
Diffculty 5

**Comment by ilikecheese117** [comment]
can this be implemented like the all fives gamemode? i.e.

`
    // Placeholder for 'allFives' rules
    getAllFivesRules() {
        return {
            // Specific validation for 'allFives' can go here
        };
    }
`

**Comment by fernandopizarro1** [comment]
> can this be implemented like the all fives gamemode? i.e.
> 
> `// Placeholder for 'allFives' rules getAllFivesRules() { return { // Specific validation for 'allFives' can go here }; }`

Yes, you should add a button so the user can select the gamemode and implement using the rule engine
