### ISSUE TITLE
Implement Tile assets into the gameplay screen

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#157]
The current state of the game visuals is not working properly. When a domino is placed vertically, the vertical dominoes overlap each other, which doesn't look good. This issue aims to fix that bug.

  -  Instead of using <div> with Flexbox, build a grid system to accurately mirror the matrix with the table's information. This will ensure that all dominoes are placed in their correct positions.
  - Use the CSS Grid property to resolve this issue.

Priority 5
Difficulty 3

**Comment by AngelCIICMorales** [comment]
Can you show me what you did?

**Comment by G4vp** [comment]
Completed this issue in PR #256.
Fixed the table layout with dominoes so they don’t overlap.
Before: 
![Screenshot from 2024-10-25 18-44-51](https://github.com/user-attachments/assets/7e2990d3-39ee-4a71-a825-4fd3d44db9e2)

After:
![Screenshot from 2024-10-25 18-46-32](https://github.com/user-attachments/assets/3718520b-a4b1-4c6f-8cc6-7039d493cc4d)

**Comment by AngelCIICMorales** [comment]
Has un pull request.
