### ISSUE TITLE
Advanced Domino Bot

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#158]
### Bot must do the following:
- Keep track of the tiles that have yet to be played on the table and the ones that have been played
- Keep track of the numbers on the tiles and their weights to make better desicions 
- Guess the opponents hand
### For the `chooseDomino` function:
- The bot must check if the tile is playable 
- The bot must check if the tile to be played benefits or detriment the players
- The bot must take into account the weight of the domino to be played
- The bot must take into account if it has tiles with the same number
- The bot must choose the best available domino depending on various factors 

Priority 5
Difficulty 5

**Comment by fernandopizarro1** [comment]
This issue was completed on PR #284

**Comment by AngelCIICMorales** [comment]
LGTM
