### ISSUE TITLE
Change the GameState to play with 3 bots

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#159]
The game currently has 2 players, the user and the bot. This issue is to change the game so it is a 4 player game instead of just a 2 player game. 

- Update the game to allow the player to play against up to 3 bots.
- Make the bots wait for their turn before placing a domino.
- Add new buttons to the game mode selection screen so the player can choose how many bots to play against.

Priority 5
Difficulty 4

**Comment by AngelCIICMorales** [comment]
Please improve the description.
