### ISSUE TITLE
[Lecture Topic Task] Example of Services present in the project

### ISSUE THREAD

**Issue by ebrain-mendoza121** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#167]
Explains services by identifying them into roles across the Multiplayer Dominoes project's various layers. Every service is stateless, defined by its function, and contains domain concepts that aren't inherently connected to any object or entity.

Difficulty = 2
Priority = 4

**Comment by ebrain-mendoza121** [comment]
An Example of Services in Multiplayer Dominoes
In Multiplayer Dominoes, when certain operations do not conceptually belong to an object. Instead, these operations are modeled as services. These services often involve multiple domain objects, and trying to summarize them in one place would affect our domain concepts. 
Examples of services and characteristics:

- Application Layer Services:

1. User Management Service:

 Is an application service, and makes user-related actions, such as creating new users, or obtaining information from existing users. It focuses on handling external user data, like in cases of the sign up or log in, and it does not involve specific domain rules. 

2. Game Room Management Service: 
Is also a service operating in the application layer, handling operations related to creating by users and joining rooms with other users. Terms like "game room" and "lobby" are key concepts in its domain.

- Domain Layer Services:
1. A domain layer service that validates core gaming characteristics, such as tile placement, and winning conditions for players. This service involves domain operations that involve business rules, like checking tile placement legality and scoring.

- Infrastructure Layer Services:
- 1. Services that are part of this layers, focus on lower level operations, such as data storage with the achievements of users, or  notification operations than can be present in the case of resetting passwords where the user would receive an email.

**Comment by AngelCIICMorales** [comment]
LGTM
