### ISSUE TITLE
[Documentation] Expand on User Stories, Epics, and New Features [2.2.1]

### ISSUE THREAD

**Issue by Gaby-Concepcion** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#169]
Elaborate on the existing documentation of User Stories, Epics, and New Features developed during the current milestone of the project. Review each user story and elaborate with explicit description of what players' needs and goals are, and what motivates them in performing some activity that would ring a bell for both novice and experienced users. Create full epics that are larger in scope and explain how these would support the greater player experience and accessibility, cultural inclusivity, and/or gameplay mechanics. Clearly outline key objectives of what should be accomplished. Document introduced features in detail with explanations of functionality and purpose, align them with project goals and diverse player base. Make sure all elements fit within the project domain definition and ensure it's culturally relevant in relation to dominoes.

**Comment by Gaby-Concepcion** [comment]
Slightly fixed some grammar from my work on the 2.2.1 section for milestone one and made the following additions:

- New user story, with corresponding approval criteria, talking about private game lobbies for the existing Multiplayer experience Epic.
- New Epic titled Enhanced solo play, focusing on the implementation of playing against 3 AI opponents.
- New Feature for the All Fives Game mode as this is quite the deviation from the standard Domino rules.

**Comment by Gaby-Concepcion** [comment]
@Keiven-Soto No se si estes disponible para verificar esto y cerrar el issue pero entiendo que tenia ya el visto bueno.

**Comment by AngelCIICMorales** [comment]
Since the maximum number of points possible is 8 for documentation you will receive that amount.
