### ISSUE TITLE
[Lecture Topic Task] Module Design in the Project

### ISSUE THREAD

**Issue by RicardoJRSs** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#175]
Describe modules for the documentation in the project according to the topics discussed in class

**Comment by RicardoJRSs** [comment]
![Image](https://github.com/user-attachments/assets/665110f1-1438-41c1-b4e4-b2bdaa095f1a)
added module design according to the domain

**Comment by RicardoJRSs** [comment]
4.8 Module Design 
In multiplayer dominoes, a module based design is necessary to keep conceptual elements together to create an interconnected design that allows us to view the many relationships these concepts share. These modules can be encompassed into the following abstract modules that offer a more comprehensive guide of the app in terms of the domain and its requirements. 

Player Management
Purpose: This module manages user/player related tasks such as registering, log in and sign up as well keeping the player’s actions registered for interactions with the interface.
Responsibilities:
Allow the users to sign up, login and register and manage this information as well as offer the user the means to execute these actions.
Keep track of logged in players, ensuring their interaction with the game and perform their desired actions
Be able to allow players easy communication, such as chatting and receiving invites
 Interactions:
It would work hand in hand with the game logic to process the user’s actions and keep the game updated in real time
Sharing the authentication data with the game state to make sure only valid players join rooms

Game Logic Module
Purpose: To manage the game’s rules and validating moves to ensure the game follows the same structure and gameplay of real world dominoes.
Responsibilities:
Validate player moves to make sure they follow the rules of dominoes
Make sure to manage the current player’s moves and notifying the other players when it's their turn and what move was just made
Track scores and determine a winner at the end
Depending on the player’s mode choices, it should support the established rules made by the player.
Interactions:
Takes actions from the player management to make sure that the player's moves are correct and the interaction is valid.
Sends updates to the game state once moves are validated and scores are calculated.
Game State Module
Purpose: Manage and update the game’s state so that the interface offers the players a real-time dominoes experience.
Responsibilities:
Track the tiles in the board and their current placements to ensure the users can perform moves accordingly
Make sure to save the game so that it can resume where it was left off in case of a pause or losing a player
Update the players hand (tiles) in real-time


Interactions:
Receives updates from the game logic whenever a move is made to ensure the necessary updates
Syncs the communication of all players to ensure they are all on the same game state.

Communication Module
Purpose: Manage real-time communication between players like in real life dominoes.
Responsibilities:
Maintain the game state synced for all existing players in a room
Provide an in-game chat to allow communication between players, an important concept in the game of dominoes.
Notify the players when it's their turn or a player wins.
Interactions:
Syncs with the game state tio keep the updates consistent
Handles chat messages and game invites with the player management module
Customization Module
Purpose: Lets players customize the look and feel of the game
Responsibilities:
Provide options to change the game rules in the game rooms to ensure a unique experience
Interactions:
Works with player management to store and apply these settings
Syncs with the game logic to make sure the rules are set on the game
Scoring and Leaderboard Module
Purpose: Manage player scores and rankings
Responsibilities:
Calculate scores based on player performance according to the rules of the game
Update the leaderboard in real time after the game finishes
Keep track winning scores, achievements and winning streaks
Interactions:
Get score updates from the game logic 
Update the player management with the latest rankings and achievements

**Comment by Keiven-Soto** [comment]
good work
