### ISSUE TITLE
[Lecture Topic Task] Add Domain Model Diagram to the documentation

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#180]
The goal is to create a Domain Model Diagram as UML that visually represents key Domain-Driven Design (DDD) concepts used in the project, such as aggregates, factories, repositories, and invariants

**Comment by Negroni1** [comment]
Added the diagram below the Domain Description in the documentation, please review @AngelCIICMorales @Keiven-Soto @ebrain-mendoza121

**Comment by Negroni1** [comment]
![Dominoes DomainModel drawio](https://github.com/user-attachments/assets/48d4e864-addb-4bde-8249-4900fcdab0a7)

**Comment by Keiven-Soto** [comment]
good work
