### ISSUE TITLE
[Lecture Topic Task] Add Layered Architecture Diagram to the documentation

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#181]
Design a layered architecture diagram that outlines the structure of the software system, incorporating four key layers: User Interface (UI), Application, Domain, and Infrastructure. This diagram will serve as a visual representation of how the system components interact, ensuring clear separation of concerns between layers.

**Comment by Negroni1** [comment]
Done! Please review, @ebrain-mendoza121 @AngelCIICMorales @Keiven-Soto 
![image](https://github.com/user-attachments/assets/24ee8040-bbe3-4e5a-9d46-1be54dc2368b)

**Comment by AngelCIICMorales** [comment]
Since the maximum score for a documentation task is 8 that is what you will receive.
