### ISSUE TITLE
[Lecture Topic Task] Refactoring Toward Deeper Insight

### ISSUE THREAD

**Issue by ilikecheese117** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#185]
This task connects the refactoring process to the Multiplayer Dominoes project by showing the changes made to the already existing codebase to implement the Draw Dominoes game mode, fix audio and gameplay bugs, and a partial refactoring of various bot and player values so they can be saved to JavaScript's LocalStorage and not be lost during page refreshes. This task is meant to explain how the programming tasks made during milestone 2 comply with the principles of refactoring toward deeper insight, as discussed in "Refactoring Toward Deeper Insight" by Marko Schütz-Schmuck.

Priority 2
Diffculty 4

**Comment by ilikecheese117** [comment]
Added:
4.8 Refactoring Toward Deeper Insight
4.8.1 Implementing the Draw Dominoes ruleset:
Draw Dominoes Game Mode:
Implicit Strategy: Adhere to Draw Dominoes 1v1 rules by focusing on game repetition mechanics for when neither of the two players have reached a score of 100, rule for game end whether player wins or loses, and scoring for the player and bot when a round is won.
Programmable Rule: Ensure a consistent draw mechanism where players draw random dominoes if no moves are available, without bugs that prevent drawing when dominoes are still accessible and bugs where the player can draw dominoes when all 28 have been utilized (this is further discussed down below).

On-Screen Score Tracker:
Implicit Strategy: Keep players informed of their current score and the bot’s current score to guide their decisions during gameplay.
Programmable Rule: Implement an on-screen score tracker component that updates in real-time, allowing players to monitor their progress toward victory.
Fixing Draw and Audio Bugs:

Fixing Getting Random Chip and Audio Bugs:
Implicit Strategy: Enhance player experience by resolving issues related to Getting Random Chips mechanics and in-game audio.
Programmable Rule: Refactor code to address bugs, ensuring players can draw randomly when there are dominoes available and audio cues work without crashing the webpage.

Partial Save-State Integration:
Implicit Strategy: Provide continuity in gameplay, allowing players to resume when refreshing the webpage and restart when leaving to the lobby.
Programmable Rule: Implement a save-state feature that offers players the option to continue from their last game or start a new one upon re-entry, storing game data reliably for future sessions.

To the document: https://docs.google.com/document/d/1-2o4vkOfsq4Kawxui-LQCJ0FLmIJ0OVVLDwCQiRsUNI/edit?tab=t.0#heading=h.shawjqwjw5im

**Comment by Keiven-Soto** [comment]
great work
