### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation - Scope, the span, and the synopsis.

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#188]
Please fix the section according to the following critique from the professor:

"The synopsis should be written so that a person who reads nothing but the synopsis still gets an idea of all the work that the project will have to do and all the artifacts that the project will produce. Imagine you direct yourself at an executive who is not willing to read more than half a page."

**Comment by Negroni1** [comment]
Done! Please review @AngelCIICMorales  @Keiven-Soto 

`Multiplayer Dominoes is a web application that replicates the authentic in-person experience of playing dominoes in a digital environment, catering to both casual and competitive players. The project will involve developing a user-friendly interface that allows players to create and customize game rooms, join matches with friends or strangers, and engage in real-time gameplay. By combining the nostalgic charm of classic dominoes with modern technology, Multiplayer Dominoes aims to create a vibrant online community where players of all ages can connect, strategize, and enjoy this game together.`

**Comment by ebrain-mendoza121** [comment]
Good Job, looks good!
