### ISSUE TITLE
Add needs to documentation based on evaluation and criteria guideline (1.2.2)

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#19]
The purpose of the section is that the developers have clear understanding of the needs independently of the system-to-be.

 It also concerns other parts of the project: is there a need for domain description, requirements prescription, software architecture, software component design, implementation, test plan, …? 

Ensure that the needs you present are not like the ideas you have for solving them. 

For more information you can read the guidelines of milestone 1 (1.2.2)

temporary scoring: 
Dificulty - 1
Urgency - 4

**Comment by AnthonyMed13** [comment]
Players require a reliable and engaging online platform to play dominoes with real-time multiplayer functionality, replicating the authentic in-person experience with smooth and intuitive gameplay. Players require a simple interface and transparent game rules to ensure fair play without technical delays. Features that promote social interaction are necessary for the continuation and spreading of the game, this would also boost the satisfaction of the players as they play  more games. There is also a need for introducing players to the game who may have never played or could have spent a long time without playing and introduce them to the standard ruleset. 
Flexibility should be taken into account as there are many variations of the rulesets given the various playstyles and regional variations of the game  Feedback is required to strive for better improvements down the line and ensure the satisfaction of the players, this could also be used to debug problems that may occur. Lastly, comprehensive development including: clear requirements specifications, robust software architecture, thoughtful design, thorough implementation, and diligent testing is essential to deliver a high-quality, reliable platform.

@JadiellMV @AngelCIICMorales Could you check the needs to see if they are good to move to the documentation?

**Comment by JadiellMV** [comment]
> Players require a reliable and engaging online platform to play dominoes with real-time multiplayer functionality, replicating the authentic in-person experience with smooth and intuitive gameplay. Players require a simple interface and transparent game rules to ensure fair play without technical delays. Features that promote social interaction are necessary for the continuation and spreading of the game, this would also boost the satisfaction of the players as they play more games. There is also a need for introducing players to the game who may have never played or could have spent a long time without playing and introduce them to the standard ruleset. Flexibility should be taken into account as there are many variations of the rulesets given the various playstyles and regional variations of the game Feedback is required to strive for better improvements down the line and ensure the satisfaction of the players, this could also be used to debug problems that may occur. Lastly, comprehensive development including: clear requirements specifications, robust software architecture, thoughtful design, thorough implementation, and diligent testing is essential to deliver a high-quality, reliable platform.
> 
> @JadiellMV @AngelCIICMorales Could you check the needs to see if they are good to move to the documentation?

Looks good to me!

**Comment by AngelCIICMorales** [comment]
LGTM.
