### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation - Domain rough sketch

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#191]
Please fix the section according to the following critique from the professor:

"Your stakeholder responses are not very helpful for understanding the domain, they are more helpful for justifying the project in the first place and maybe as a source for requirements. But they do not really tell us much about the domain and how it works."

Scoring
Urgency: 4
Difficulty: 4

**Comment by rukitoyordan** [comment]
Added the following:

> This notice takes into account what dominoes as a game works as a whole. These specific comments suggest that interaction in a social manner adapt towards the domain of this project. It also ties down the aspect of pacing the gameplay to give room for the conversations and the strategic thinking that is a fundamental for the game that is being portrayed. Certain things like the tile counting mentioned above are indicators on how the domain itself works. Adding to this, there is an aspect of possible “Onboarding” which can be explored so that the domain is approached with the cultural importance and the way dominoes works as a game that exists already and is being sampled on the project’s end. 
> Some keys to what the domain rough sketch entices that a possible newer interview may be needed in order to capture the aspects of the dynamics of dominoes, the social experience that is sought of replicating, and the connections between the original game in the domain and its implementation.

Adding to this, I believe possibly for M3, a more tailored interview that aligns to the professor's comment and some feedback on the responses can better help us fix this portion of the documentation. Instead of fully scrapping the interviewees responses, they can be repurposed for other sections that would enchance better the justification of the project itself.

**Comment by rukitoyordan** [comment]
Let me know if there is more I should elaborate on or not!

**Comment by AngelCIICMorales** [comment]
Please add the changes in the description.

**Comment by rukitoyordan** [comment]
The changes have already been added to the M2 Documentation in that section at the bottom after the interviewers statements. Commented above is what we added as well.
