### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation -  Describe events, actions, and behaviors.

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#192]
Please fix the section according to the following critique from the professor:

"If you claim that a concept is a behavior, then you have to motivate that. One way to motivate this would be by showing the actions and events that make up the behavior. That way we can see that it really is a behavior. Of course, the actions and events must be such that they of relevant to the domain. For example, "play turn" could be the name of a behavior that we take to be the entire play during one turn that the player plays. To motivate that this is a behavior we could show: player becomes aware of all the places where they could play a tile, player has just become aware of all possible moves, player decides on which tile to play, player has just decided on which tile to play, player plays their chosen tile, player has just played their tile (which ends their turn). I do not know whether that actually does the reality justice, but it illustrates the important points: actions and events interleaved, each action or event is meaningful for the domain.

Rule variation seems quite vague as an entity.

Events, actions, and behaviors have the same relevance to the domain as the entities. It's even the case that often, whether something is seen as a entity or as an action, is just a matter of personal view. We can, for example, talk about "the transfer" of funds from one account to another (entity) or about "to transfer" funds from one account to another. In the first case we take the view that "a transfer" is an entity (and we would then implement it as a class with the instances representing the transfers). In the second case we take the view that "to transfer" is an action/operation/function that we carry out on funds and two accounts (and we would then implement is as a function with the corresponding parameters and results). Therefore, it does not make sense to separate the events, behaviors, and actions for the entities and, instead, they should be presented within the same section.

The first three events are not clearly instantaneous. We can easily misunderstand them and take them to be actions. "Decides" can be seen as the process of thinking over and coming to a decision, in which case this would clearly be an action. But it can also, and you most likely intended it to be read like that, be seen as the moment a person has reached that decision. In order to prevent such misunderstandings you must be very disciplined with the use of language.

The join or create game action that you describe is very much only about the interaction with the app. But it would also make sense to see this action on the level of the domain, what does it mean the join a game in terms of domain concepts?

The behaviors that you show here could also be seen as functions, it depends on whether we see any actions and events that make up the behaviors in such a way that these are relevant to the project (and to the domain)."

**Comment by RicardoJRSs** [comment]
![Image](https://github.com/user-attachments/assets/e2b55735-9799-401f-b40d-bea566bb9a68)
added new a format ,completely modified the structure and deleted the old one according to the professor feedback

**Comment by AngelCIICMorales** [comment]
I will lower your points to 8 since that was the agreed upon maximum score.
