### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation - User Stories

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#196]
Please fix the section according to the following critique from the professor:

"You have cultural and generational inclusivity, but what about accessibility?

Be careful with the approval criteria: "players are able to" can be misinterpreted to require something of those people who play..."

**Comment by print-Eruki** [comment]
Added and eliminated bullets on section 2.1.1 "user stories". Make distinction of interfaces and system. And address the professors comments regarding accessibility. 
![image](https://github.com/user-attachments/assets/ba3bd8b6-b3ec-48f9-a70b-3817da90bdd6)

**Comment by AngelCIICMorales** [comment]
I don't see your changes reflected on the documentation.

**Comment by print-Eruki** [comment]
Changes can be found at section 2.2.1 of the documenation, here is another snippet of my changes.
![image](https://github.com/user-attachments/assets/5cc77e90-3e5b-4d4a-955e-eafd44511cce)

**Comment by ebrain-mendoza121** [comment]
Looks good!

**Comment by AngelCIICMorales** [comment]
LGTM
