### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation - Domain Requirements

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#197]
Please fix the section according to the following critique from the professor:

"In the requirements you have "the system must" only then to fall back to "allow"...

Many of your domain requirements are too big, too broad to be assigned you just one category. For example, take "The system-to-be must calculate scores based on standard dominoes rules and display a leaderboard." there are domain aspects in this (e.g. that there have to be functions that calculate scores), but there are also other aspects in this. One would be the display of the leaderboard."

**Comment by Negroni1** [comment]
Done! Please review and close, @AngelCIICMorales @Keiven-Soto

**Comment by ebrain-mendoza121** [comment]
Great job! Add the changes made, here in description when possible.

**Comment by Negroni1** [comment]
Ok! Please review! @ebrain-mendoza121  @AngelCIICMorales @Keiven-Soto 

- The system must support a 4-player multiplayer mode. 
- The system must  enable users to connect and play in real-time.
- The system  must provide automatic matchmaking for players.
- The system must let users invite others to join private games. 
- The system must enforce the rules of dominoes.
-          The system must validate tile placement.
-           The system must manage the player's turn.
-           The system must keep the scoring.
- The system must display  real-time updates for all players.
- The system must manage  player turns sequentially.
- The system must notify  players when it is their turn.
- The system must prevent  actions outside the player’s turn.
- The system must calculate scores based on standard dominoes rules.
- The system must provide a leaderboard that displays player rankings.
- The system  must implement user authentication.
- The system must facilitate the creation, joining, and leaving of game rooms.
- The system must manage the safe states of the board.
- The system must ensure that games can be paused and resumed without losing progress.

**Comment by ebrain-mendoza121** [comment]
Looks good!

**Comment by AngelCIICMorales** [comment]
LGTM
