### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation -  Machine Requirements

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#199]
Please fix the section according to the following critique from the professor:

"Your platforms requirements might just not be requirements. From where do you derive these? It seems implausible that your stakeholders told you that you must use these technologies. To me it looks more like these are platform _decisions_ that you made. Nothing wrong with that, just has to go somewhere else. On the other hand, the latency for gameplay is definitely a machine requirement. From it you might be able to justify some of the implementation decisions..."

**Comment by print-Eruki** [comment]
Task is up for review @Keiven-Soto @AngelCIICMorales. The changes made were: 

- Proper machine requirements divided in system-to-be requirements
- Added a new section called platform decision talking about tech stack
- Eliminated irrelevant information from the machine requirements

**Comment by AngelCIICMorales** [comment]
Please send an image of the changes.

**Comment by print-Eruki** [comment]
![Screenshot from 2024-10-09 19-37-27](https://github.com/user-attachments/assets/43f1566b-92a1-4773-8956-d1c3c4ef2ae3)

This is part of the changes, the changes are too big to be on a single picture, if needed more screenshot I can provide them!

**Comment by Keiven-Soto** [comment]
ok it looks good now

**Comment by AngelCIICMorales** [comment]
Since the maximum points for documentation are 8 that is what you will recieve.
