### ISSUE TITLE
[Documentation Fix] Fix Milestone 1 Issues with Documentation - Concept Analysis and Terminology

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#201]
Please fix the section according to the following critique from the professor:
"On the choice of terms: "game preference" sounds like something that a person has/holds. But when I read what you write here, I understand that that's not what you mean. While the players have preferences for some types of games it's really an attribute of the game. So, it would be good to have a term that reflects this. Like "game options" or "game characteristics" or similar..."

**Comment by RicardoJRSs** [comment]
![Image](https://github.com/user-attachments/assets/eaa90c4f-b847-4794-ae3e-4bc5e48d09c7)
