### ISSUE TITLE
[Lecture Topic Task] Add Factories to the Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#204]
This task is part of Milestone 2 Guidelines section of "Application of topics, techniques, tools, methods, … from the lectures", as such is it is a Lecture Topic Task.
The task entails to add to the documentation document the aggregates as detailed in the guidelines and as discussed in class:

    The team provides at least one example of the application of
    factories. For example, they might initially expose the directly the
    constructors of different sub-classes of some super-class. But then
    they decide that the construction should be hosted in a separate
    factory class with an API providing entry points behind which
    complex choices are made as to which concrete object to instantiate.

Score:
Urgency: 4
Difficulty: 2

**Comment by Gaby-Concepcion** [comment]
Added the 4.4 and 4.4.1 section to the documentation to discuss how the game mode selection centralizes the creation of game mode instances, and how it manages complexity behind a single interface.

Included a sequence diagram (see attached image) to visually represent the interaction between the system components to help clarify the flow of interactions and the role of the factory in managing game mode selection.

> -    User: Accesses the game state and makes a game mode selection.
> -     GameState: Retrieves available game modes and initiates the selected game mode.
> -     GameModeSelection: Provides the list of available modes and applies the selected mode's corresponding rules.
> -     GameModeRuleEngine: Fetches and applies specific rules for the selected mode.

I also realized some others lecture topic task had to do with factories which are 4.4.2 and 4.4.3 respectively.
