### ISSUE TITLE
[Lecture Topic Task] Add Repositories to the Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#205]
This task is part of Milestone 2 Guidelines section of "Application of topics, techniques, tools, methods, … from the lectures", as such is it is a Lecture Topic Task.
The task entails to add to the documentation document the aggregates as detailed in the guidelines and as discussed in class:

    The team uses repositories to expose an interface providing
    persistence related functions in terms of the domain and/or the
    application layer.

Score:
Urgency: 4
Difficulty: 2

**Comment by print-Eruki** [comment]
Added a new section called "Repository Pattern and Aggregates" addressing the professors feedback. 
- Added Aggregates for modeling
- Repository pattern for data consistency
- Integration of Aggregates and Repository Pattern
![image](https://github.com/user-attachments/assets/e7dec719-c927-4bb6-8ee0-b5ff64693f76)
Ready for review: @Keiven-Soto @AngelCIICMorales @ebrain-mendoza121

**Comment by AngelCIICMorales** [comment]
LGTM
