### ISSUE TITLE
[Sign In Team] Implement a user registration form on the frontend.

### ISSUE THREAD

**Issue by JadiellMV** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#21]
Create a form on the frontend where new users can enter their registration details, such as username, email, and password.

Steps to Fulfill: Design a user-friendly form layout. Add input fields for username, email, and password. Implement error handling for invalid inputs or missing fields.

Urgency: 3
Difficulty: 3

**Comment by AngelCIICMorales** [comment]
What am I reviewing?

**Comment by AngelCIICMorales** [comment]
Ah, I'm sorry. I noticed this is linked with the pull request.

**Comment by sandy-marrero** [comment]
PR has been merged with main, issue is ready to be closed. @Keiven-Soto @AngelCIICMorales
