### ISSUE TITLE
[Lecture Topic Task] Applying Clean Architecture to Game Mode selection screen.

### ISSUE THREAD

**Issue by Jvstinoo** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#219]
This task relates to the Clean Architecture lecture, specially the Open-Closed Principle. The placeholder screen is designed to allow easy extension of new modes without modifying the existing code. 

The UI layer is separated from the rule validation provided by the RuleEngine, which ensures that new game modes can be added without having to rewrite the system.

**Comment by Jvstinoo** [comment]
Added documentation here: https://docs.google.com/document/d/1-2o4vkOfsq4Kawxui-LQCJ0FLmIJ0OVVLDwCQiRsUNI/edit?tab=t.0#heading=h.jka5b5oltr3c

**Comment by AngelCIICMorales** [comment]
LGTM
