### ISSUE TITLE
Add other activities than just developing source code (1.4)

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#22]
For this task you need to include all the activities that are not related to writing source code. 

A couple of examples for task like this are: domain and requirements engineering, software architecture, component design, implementation, testing, deployment, ... 

Your project will also concern itself with domain and requirements engineering, software architecture, component design, implementation, testing, deployment, … Since these are all things you will do, what are your ideas about these points, what specific needs are there that are satisfied by doing these things, and what about the current situation brings about these needs. 

For example, part of the ideas is to implement a system. Then that implementation needs requirements in order to specify what functionality needs to be implemented.

For more information you can read the guidelines of milestone 1 (1.4)

Temporary Score:
Urgency - 4
Dificulty - 2

**Comment by AnthonyMed13** [comment]
Other Activities Beyond Developing Source Code

Aside from developing the source code, we worked on domain development, requirements engineering, and software design. Initially, the team lacked in-depth knowledge about the project's main subject, so we researched the domain thoroughly to fill these knowledge gaps and build a solid foundation. With the domain developed, we could identify the basic requirements needed for the users. Gathering these requirements provided developers with a clear understanding of the system's expected functionality, defining the scope, and preventing misunderstandings during development. Once we had all of that, we started designing the platform to create a rough sketch. That could be used for the concept analysis as a good base.

We will also test different parts of the implementation via various means. This approach will ensure that everything runs as expected and allow us to detect and resolve any major problems early on, reducing the risk of unanticipated issues during final deployment. We will also conduct A/B testing and gather feedback from users, this will help us make data-driven decisions and refine the product based on real user input. This process will ensure that the requirements from our domain, interface, and system functionality are met effectively, enhancing overall user satisfaction.

By addressing these specific needs through domain development, requirements engineering, software design, and thorough testing, we will ensure that our project is well-founded, aligned with user expectations, and free of major issues upon deployment.

@JadiellMV @AngelCIICMorales Hi if you could review this before adding it to the documentation. Also this was easier than expected so we could reduce the difficulty to 1 instead of 2

**Comment by AngelCIICMorales** [comment]
I will give you 6 points. What you wrote seems alright with me.
