### ISSUE TITLE
[UI Team] Modify the multiplayer leaderboard visually to better match the domino aesthetic

### ISSUE THREAD

**Issue by DavidCuevas3** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#220]
The basic asset for the multiplayer leaderboard was completed in the previous milestone, however, it was a basic design and lacked the visual aesthetic of the dominoes game. For this issue I will make use of wooden aesthetics to match the feel of the domino board and elements.

Difficulty 2
Priority 3

**Comment by DavidCuevas3** [comment]
Attached are the screenshot for the new asset and the link to the figma:
![Screenshot 2024-10-06 145412](https://github.com/user-attachments/assets/41cb5d70-964c-4631-98ab-d6d5df0064db)
https://www.figma.com/design/9tB7x524EnEF8I57CyxoMg/Colors%2C-Defaults%2C-Screens?node-id=126-2&t=y7Y2rFo8RwsnEMiS-1

**Comment by PinkSylvie** [comment]
I'm concerned since I don't know how well realistic wood textures will match with the pixel aesthetic of the site

**Comment by DavidCuevas3** [comment]
Understood, I pixelated it slightly. Screenshot is attached.
![image](https://github.com/user-attachments/assets/48749f4c-2968-4a90-bbc2-f051f8eb705f)

**Comment by AngelCIICMorales** [comment]
Why is there a blue square on the right side of the image?

**Comment by DavidCuevas3** [comment]
> Why is there a blue square on the right side of the image?

It's how figma shows when an element is selected. The block was accidentally selected when I took the screenshot.

**Comment by AngelCIICMorales** [comment]
I'm not really sure of the current design since the brown doesn't look that good with the wood. Do you believe you will be able to make some changes before the end of the sprint? If not, I'll approve it now but please make sure to modify it.

**Comment by DavidCuevas3** [comment]
I was thinking of maybe adding some texture to the brown or changing the color. I dont know how long it might take but if it sounds like a good change I can start working on it right away.

**Comment by AngelCIICMorales** [comment]
That sounds like it would be a good change. Let me know when you are done so I may approve your task ASAP.

**Comment by DavidCuevas3** [comment]
Went with a lighter color to avoid contrast with the light wood color and also added texturing. The orange cubes also adhere more to the aesthetic the other assets share.
![image](https://github.com/user-attachments/assets/ce8e7c59-3d79-43df-b722-b031e6b918eb)

**Comment by AngelCIICMorales** [comment]
It looks better now. I think if the wood texture was a bit darker it would look even better, but I'll approve it for now.
