### ISSUE TITLE
[Lecture Topic Task] Bridging Model and Implementation: Challenges in Developing AI-Driven Game Systems

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#224]
This topic explores the complexities of connecting conceptual models to their practical implementation in AI-driven game systems. While the associations between objects such as players, game state, and resources may seem straightforward, deeper challenges arise in ensuring consistent and efficient behavior. Using a DominoBot class as a case study, the discussion covers:

- Implementing associations between game components (e.g., the bot, table, and hand).
- Managing dynamic interactions between objects to maintain game state.
- Addressing challenges such as concurrency, decision-making logic, and edge cases in real-time game environments. The focus is on how robust design strategies can ensure smooth gameplay and scalable AI behavior.

**Comment by fernandopizarro1** [comment]
The Lecture Topic was added in the documentation under the title: 
### Bridging Model and Implementation: Challenges in Developing AI-Driven Game Systems
The following criteria is a part of this lecture topic:
- Implementing Associations Between Game Components
- Managing Dynamic Interactions Between Objects
- Addressing Challenges in Game Logic and Scalability

https://docs.google.com/document/d/1-2o4vkOfsq4Kawxui-LQCJ0FLmIJ0OVVLDwCQiRsUNI/edit?usp=sharing

**Comment by AngelCIICMorales** [comment]
LGTM
