### ISSUE TITLE
[Lecture Topic Task] Research and write potential user stories focused on accessibility.

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#229]
- Research cases of users with various types of disabilities and explore how we can make our game more accessible for them.

Urgency: 4 pts
Difficulty: 2pts

**Comment by G4vp** [comment]
Added new approval criteria focused on accessibility features in the user stories in the documentation.

**Comment by AngelCIICMorales** [comment]
Please send the changes in the description.

**Comment by G4vp** [comment]
###Text added by me is in bold.

Epic 2: Cultural and Generational, and Accessibility Inclusivity
	A player wants to enjoy the game with rules and a game style similar to classic Puerto Rican Dominoes in order to share it with the elders in their family, **while ensuring the game is accessible to players with various disabilities.**
Description: This epic is about keeping traditional domino rules and building an experience that will be appealing for the older generation who already knows the game, and to the newer generation who may learn it. **Additionally, the game will implement accessibility features to accommodate players with visual, auditory, cognitive, and motor disabilities. The interface will prioritize user-friendly designs for players of all ages and abilities.**
User Story #1: Customizable Rule Sets
“As a player, I would like to play the game with the traditional rules of Puerto Rican domino along with the popular house rules, so I can relive and preserve the way I have always played it with my family.”
Approval Criteria:
The game uses a default rule set based on traditional Puerto Rican dominoes. The interface is accessible, with clear rule customization options, and includes tooltips or audio descriptions for players with disabilities.
With such a feature, players can turn on some extra rules if they feel like playing other popular house rules. 
**The interface should allow for rule customization in an accessible and easy-to-navigate format, providing tooltips or audio descriptions for players with visual or cognitive disabilities.**
User Story #2: Accessibility-friendly Interface for Any Age
	"As a player, I don't want to be lost in menus and just want to easily navigate the game interface so that both younger players and older players can enjoy the game."
Approval Criteria:
The UI should be clear, accessible, with large buttons and text. The interface is accessible, with clear rule customization options, and includes tooltips or audio descriptions for players with disabilities
The interface’s design should be intuitive and not obscure anything by confusing menus or controls.
**Optional features such as colorblind modes and customizable sound settings should be provided for players with specific needs (e.g., hearing impairments or sensitivity to sounds).**
