### ISSUE TITLE
[Sign In Team] Implement a logout feature that ends user sessions.

### ISSUE THREAD

**Issue by JadiellMV** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#23]
Ensure users can securely log out, and all session information is cleared.

 Steps to Fulfill: Set up a backend endpoint to handle logout requests. Redirect the user to the login page or a logged-out state.

Urgency: 3
Difficulty: 3

**Comment by sandy-marrero** [comment]
task was completed by another issue, closed
