### ISSUE TITLE
Create Powerpoint Presentation  for the Milestone 2 Presentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#236]
The milestone ends in Oct 24th. After the milestone ends, speak with the managers @AngelCIICMorales and @Keiven-Soto to discuss what the team accomplished this milestone to show off in the video presentation that will be shown to the professor on Sept 23rd. You'll have till Oct 27th to submit the video but as the milestone will be over before then, the task score will be set for milestone 3

This presentation will need to show how we've accomplished the goals we set for the milestone and what will be the goals for the next milestone. You can use the previous milestone's presentation available in the team drive as a template and as reference.

**Comment by Negroni1** [comment]
@AngelCIICMorales @Keiven-Soto @PinkSylvie @ebrain-mendoza121 @fernandopizarro1 Please review the slides: https://docs.google.com/presentation/d/1gaPUG1Ee8kT8ZQEdsgKEh8t7MIubwggNGS2Joh0BxrQ/edit?usp=sharing

**Comment by fernandopizarro1** [comment]
> @AngelCIICMorales @Keiven-Soto @PinkSylvie @ebrain-mendoza121 @fernandopizarro1 Please review the slides: https://docs.google.com/presentation/d/1gaPUG1Ee8kT8ZQEdsgKEh8t7MIubwggNGS2Joh0BxrQ/edit?usp=sharing

Presentation covers everything from my team! 👍

**Comment by PinkSylvie** [comment]
It looks great! @fernandopizarro1 make sure to add what will your team be working on in the future work slide for it. Same goes for @ebrain-mendoza121
