### ISSUE TITLE
[Lecture Topic Task] Add closure under operation

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#243]
The team shows how they worked towards closure under an operation. They show an initial situation in which a class depended on various other classes or types. They also document how they changed this class to close it with respect to its operations (or at least make it depend on much fewer other classes

Tentative points:
Urgency: 4
Dificulty: 1

**Comment by AnthonyMed13** [comment]
While inspecting various areas of our code we found that the UserHandler portion could be modified inorder to rely less on other classes. This could be achieved by encapsulating external dependencies within the helper methods in the UsersHandler class bringing several long-term benefits, although applying this with the given time constraints was not feasible. This approach would increase modularity by making operations self-contained, simplifying future updates and maintenance. By managing tasks like token verification and password hashing through internal methods, the class also becomes more testable, allowing for focused unit tests and more reliable results. The reduced dependency coupling means the class is less affected by updates to external libraries, making future modifications, like switching hashing libraries, far simpler. Better code organization using internal helper methods also improves readability and maintainability, making it easier for future developers to browse and comprehend the codebase. Understanding these advantages now offers helpful direction for prospective refactoring initiatives in the future, particularly when the project grows or resources permit, aligning with best practices for creating modular, maintainable, and resilient code.

**Comment by AnthonyMed13** [comment]
@AngelCIICMorales @Keiven-Soto @ebrain-mendoza121 Can you check this to close the issue and added to the documentation

**Comment by ebrain-mendoza121** [comment]
Looks good!

**Comment by AngelCIICMorales** [comment]
Only one person can be assigned to a lecture topic task

**Comment by AnthonyMed13** [comment]
> Only one person can be assigned to a lecture topic task

fixed
