### ISSUE TITLE
[Sign In Team]  Design the lobby creation interface for users to create or join rooms.

### ISSUE THREAD

**Issue by JadiellMV** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#25]
Create the visual elements and interactive components that allow users to create or join game rooms. 

Steps to Fulfill: Design the lobby UI. Implement the lobby page with options for creating a new room or joining existing rooms. Use a frontend framework to handle room creation and joining actions.

Urgency: 3
Difficulty: 4

**Comment by Keiven-Soto** [comment]
can you attach an image in the comments of the visual elements? Once that is attached I can close the issue

**Comment by ebrain-mendoza121** [comment]
![image](https://github.com/user-attachments/assets/a98b1678-6e09-4f07-a4e9-dff16feba332)
