### ISSUE TITLE
[Lecture Topic Task] Add Other Patterns to Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#254]
This task is part of Milestone 3 Guidelines section of "Application of topics, techniques, tools, methods, … from the lectures", as such is it is a Lecture Topic Task.

The task entails to add to the documentation document the Other Patterns besides those mentioned before in the guidelines as detailed and as discussed in class:

  _"The team shows examples of at least one other pattern (composite,
  transaction,…)  from the analysis patterns discussed in class. An
  example would be locations within locations. Just for example, say we
  wanted to state where within an super market chain an item is
  located. We could have an initial "locator" indicating the individual
  store of the chain in which the item is located. Below that we might
  have a locator that indicates a location within the store, say the
  high level area (storage, shelves, unloading dock,…). Then some of
  these might contain another level of sub-division. For example,
  shelves divided into aisles, aisles into sections, sections into
  floors."_

**Comment by PinkSylvie** [comment]
@AngelCIICMorales @Keiven-Soto I added what I needed to complete this task in the section 4.9.1 of the documentation. It is added as Composite Pattern as it is one example of a pattern aside from those in the guidelines.

**Comment by Keiven-Soto** [comment]
great work!
