### ISSUE TITLE
Add concept analysis to the documentation (3.1)

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#26]
The concept analysis is a more refined version of the rough sketch, you find and introduce concepts that you think arise from the rough sketch. You document the decisions taken to simplify concepts into general subjects. Example a brand of a car to the concept Vehicle.  One most also find the common concepts bewteen different topics obtained from interviews, common knowledge, ...

Also in that section you identify potential clashes: maybe someone is using a term in one way and someone else uses the same term in the (slightly?) different way. Are these compatible? Can a common base be found?

For more information you can read the guidelines of milestone 1 (3.1)

Temporary Scoring:
Urgency - 4
Dificulty - 2

**Comment by AnthonyMed13** [comment]
Players: Players are the users that will play the dominoes game. Taking into account the rough sketch, we can see that some players prefer to play with friends, and family. Although some players don't mind and also like to play with other random players. This means that Players can contain both needs for social interaction between known and unknown Players. This highlights the need to accommodate both private games with known contacts and public games with random players. 

Game Preferences: Game preferences is about the aspects of the game such as game length, style, and competitiveness. Taking into account the rough sketch some players enjoy more casual games, meanwhile others prefer more strategy to be involved. Some even enjoy competitive elements like rankings and leaderboards, and others play purely for fun without focusing on competition. This shows the importance of offering customizable game settings within the app to suit various playstyles and keep players engaged according to their individual preferences.

Learning Methods: Learning Methods are the different ways players learn to play dominoes or get better at the game. From the rough sketch, players like intuitive tutorials, written rules, video guides, and watching others play. This shows that everyone learns differently and wants to enjoy the game more. To support this, the app should include various learning tools like interactive tutorials or easy to read tutorials. This way, new players can learn the basics, and experienced players can get better at the game.
Customization: Customization is about letting players personalize their gaming experience with things like avatars, themes, and in-game settings. The rough sketch indicates that some players love customizing their game environment, while others prefer a simple setup. To cater to both types, the app should offer optional customization features. This means players who enjoy personalizing can do so, and those who don’t can stick with the standard look. Providing this choice helps keep all players happy and engaged.
Competitiveness and Motivation: Competitiveness and Motivation cover features like leaderboards, rankings, and other competitive elements that encourage players to keep playing. According to the rough sketch, some players are driven by competition and want to climb the rankings, while others just want to play casually without worrying about their standings. By grouping these into Competitiveness and Motivation, it’s clear that competition is important for many players but not everyone. The app should include competitive features as optional, so players can choose to participate in rankings and leaderboards if they want to, while others can enjoy the game without the competitive pressure.


Potential Clashes:

Since the project is still in its early stages there are not a lot of clashes that we can detect one that was noticeable was the rulesets. Some people learned dominoes in different places from different people, leading them to have learned different rules than the ones we may be using. We will have to focus on clarifying and allowing different rulesets in the Game Preferences to ensure that everybody can enjoy the game.

@JadiellMV Please verify that this is good before adding to the documentation

**Comment by AngelCIICMorales** [comment]
LGTM.
