### ISSUE TITLE
[Lecture Topic Task] Making Implicit Concepts Explicit in the GameMode

### ISSUE THREAD

**Issue by nsfrontera** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#261]
This task connects to formalizing implicit gameplay strategies discussed in the lecture on Making Implicit Concepts Explicit by defining clear, programmable rules for the game mode. In the lecture, it was emphasized that implicit concepts often remain hidden within informal or intuitive actions, and it’s the job of developers to bring these concepts to the surface. By creating explicit rules for All Fives and Classic Dominoes, we translate strategic, experience-driven behaviors into precise models that can be understood, optimized, and implemented programmatically. This shift from implicit to explicit allows for deeper insights, cleaner game designs, and even the potential to refine or optimize strategies through computational means.

Tentative Points:
Urgency: 4
Dificulty: 1

**Comment by nsfrontera** [comment]
Classic Dominoes

1. Maximizing Plays:

- Implicit Strategy: Players aim to use as many dominoes as possible to avoid accumulating points.

- Programmable Rule: If multiple moves are possible, select the move that allows for the highest number of dominoes to be played in future turns (minimizing unplayed dominoes).

2. Blocking Opponents:

- Implicit Strategy: Players try to block opponents from playing by restricting available moves.

- Programmable Rule: If a play can limit the opponent’s options by reducing open numbers on the board, prioritize this move.

3. Maintaining Balance:

- Implicit Strategy: Keeping a balanced hand, with numbers that can match a variety of tiles.

- Programmable Rule: Avoid holding a large number of high-value or duplicate tiles, which could limit future plays.

All Fives (Five-Up Dominoes)

1. Scoring Multiples of Five:

- Implicit Strategy: Aim to score points by ensuring the sum of the open ends of the board is a multiple of five.

- Programmable Rule: Always calculate the sum of open ends, and prioritize moves that result in multiples of five for points.

2. Setting Up for Future Points:

- Implicit Strategy: Prepare the board to maximize future scoring opportunities.

- Programmable Rule: When no immediate scoring is possible, prioritize moves that keep multiple ends open with numbers that are more likely to lead to multiples of five in subsequent turns.

3. Defensive Play:

- Implicit Strategy: Prevent opponents from scoring by not leaving numbers that could result in a multiple of five.

- Programmable Rule: When unable to score, choose moves that reduce the opponent's chances of scoring, like avoiding plays that leave common multiples (5, 10, etc.) as open ends.

**Comment by nsfrontera** [comment]
added here:
https://docs.google.com/document/d/1-2o4vkOfsq4Kawxui-LQCJ0FLmIJ0OVVLDwCQiRsUNI/edit?tab=t.0#heading=h.vg3tj06pvlz7

**Comment by AngelCIICMorales** [comment]
LGTM
