### ISSUE TITLE
Create Gameplay team slides/General slides for the Powerpoint for the Milestone 3 Presentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#282]
The milestone ends in Nov 27th. After the milestone ends, speak with the managers @AngelCIICMorales and @Keiven-Soto to discuss what the team accomplished this milestone to show off in the video presentation that will be shown to the professor on Nov 29th. You'll have till Nov 29th to submit the video but as the milestone will be over before then, the task score will be set for milestone 3

This presentation will need to show how the Auth team accomplished the goals we set for the milestone and what will be the goals for the next milestone. You can use the previous milestone's presentation available in the team drive as a template and as reference.

**Comment by sandy-marrero** [comment]
[Presentation Link](https://docs.google.com/presentation/d/11t_c-BL3DJtAqqp4CFeoaMybv27UlTah0qqlv-8jVY0/edit?usp=sharing)

Started work on the general content of the Milestone 3 presentation and the specific topics to highlight for the game state. WIP

**Comment by sandy-marrero** [comment]
@Keiven-Soto @AngelCIICMorales
