### ISSUE TITLE
[Lecture Topic Task] Add stand-alone classes to project and documentation

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#288]
Based on the documentation guidelines, add to the documentation the stated below by the professor: 

"  The team shows examples where initially they had a class with several
  dependencies and then they worked towards making these dependencies
  unnecessary so they could drop them. This might involve the use of
  other patterns. "

**Comment by PinkSylvie** [comment]
The following thing that was needed for the documentation based on the guidelines was missing so I took the liberty to edit the description to assign you the task as you were missing one.

**Comment by FrancesC8** [comment]
@AngelCIICMorales @ebrain-mendoza121 I added a new section `4.21 Stand-Alone Classes` in the documentation, please review and let me know.
