### ISSUE TITLE
[Lecture Topic Task] Making Implicit Concepts Explicit for new Game Modes

### ISSUE THREAD

**Issue by Gaby-Concepcion** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#289]
This task focuses on expanding the 4.5 section of the documentation, _'Making Implicit Concepts Explicit'_, by including the draw dominoes game mode, along with any game modes that may be added during this final milestone. As was stated on issue #261, "In the lecture, it was emphasized that implicit concepts often remain hidden within informal or intuitive actions, and it’s the job of developers to bring these concepts to the surface.", by defining a clear and programmable rule for the draw dominoes game mode; in addition to any additional game mode developed and implemented during the milestone. By creating and adding the rules for these missing game modes, we can have a more complete and holistic view of the project and we translate strategic, experience-driven behaviors into precise models that can be understood, optimized, and implemented programmatically. As stated in the parent issue "This shift from implicit to explicit allows for deeper insights, cleaner game designs, and even the potential to refine or optimize strategies through computational means."

Tentative Points:
Urgency: 1
Difficulty: 1

**Comment by Gaby-Concepcion** [comment]
Included the 'draw dominoes' game mode within the Implicit to Explicit section of the documentation under section 4.5. Primarily outlined strategies for controlling the flow of the game and shifting the unknown and risky aspect of this game mode in your favor.

**Comment by AngelCIICMorales** [comment]
LGTM
