### ISSUE TITLE
[Lecture Topic Task] QA stakeholders to solve 1st Order of ignorance issue and add Domain Rough Sketch to Documentation based on QA (2.1.1)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#3]
The 1st Order of ignorance states that _"Lack of Knowledge
I have First Order Ignorance (1OI) when I don’t know
something but I know I don’t know it. 1OI is actually a
kind of knowledge (I do know what I don’t know)."_

As we are in the first stage of our project, as a team we know that we don't know what composes our project's domain. That is the reason we are QA our stakeholders to have a better idea of what our domain entails, as such solving this 1st order of ignorance issue. 

The 'rough domain sketch' would include the specifics that you were told. The domain rough sketch refers to an application: the domain is that part of the observable universe that is of interest to your project, but independent of a system-to-be. Rough sketches are for collecting unprocessed information for example from brainstorming sessions, interviews, literature review, …

QA with potential users of the site to gather information to write the rough sketch. Not asking what they would think about it but their experiences in doing actions related to the domain, not the application. Then focus on what feature you can gather and write them down in the documentation.

Include in this task the results of the QA. 

Scoring:
Difficulty - 4
Urgency - 4

**Comment by PinkSylvie** [comment]
Hello! @AngelCIICMorales and @Keiven-Soto, I finished adding this section into the documentation, for it I read thru the answers and for each interviewee I glued the answers together in a way to make a small paragraph for each based on the answers given. I added the results overview in a [document](https://docs.google.com/document/d/1mg0veQhp4c-EwL5zZG__v5Cg_P6k5RITNGGhjpK_AZ4/edit?usp=sharing) that is in the [shared drive folder.](https://drive.google.com/drive/folders/11OBD1nDHeBYVdclDCg-PdbFd0ctfcfiZ?usp=sharing) . Please review as soon as you can to close the task and if there is any issue don't hesitate to reach out.

**Comment by AngelCIICMorales** [comment]
Good job!
