### ISSUE TITLE
[Lecture Topic Task] 4.4.3 Add Additional Factory Applications

### ISSUE THREAD

**Issue by Gaby-Concepcion** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#314]
Expand on additional Factory Applications, under section 4.4.3 of the documentation. 
The current system of achievements and AI behaviors is inflexible and non-extensible. Achievements are hard-coded, and making it difficult to add new triggers or rewards easily without changing any existing code. Similarly, AI behaviors are tightly coupled with game logics, making the addition of new difficulty levels and/or user-defined strategies for certain game modes painfully difficult.

For this, we could implement an Achievement Factory, which can dynamically instantiate different achievement instances, based on the gameplay events, milestones, or even players' actions. Additionally, an AI Behavior Factory will handle the instantiation of AI agents with strategies applicable to certain difficulty levels or game modes. These factories would focus on centralizing creation logic, enhance flexibility, and improve maintainability.

**Comment by AngelCIICMorales** [comment]
LGTM
