### ISSUE TITLE
[Lecture Topic Task]  Fix Paragraph in Section 4.2.1: Implementing Associations Between Game Components

### ISSUE THREAD

**Issue by G4vp** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#315]
Based on the professor's feedback, some paragraphs in section 4.2 seem vague and somewhat bloated. This task focuses on revising those paragraphs to add more information and improve clarity.

1 difficulty * 1 urgency = 1 pts

**Comment by G4vp** [comment]
![image](https://github.com/user-attachments/assets/1856db4b-0e6c-49e0-bd6d-1e6270217ac1)

**Comment by AngelCIICMorales** [comment]
I have raised your points to 4.
