### ISSUE TITLE
Add domain requirements in the documentation (2.2.3)

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#32]
Domain requirements are derived from observations of the domain and the decision or the insight that a phenomenon or concept needs to be  "simulated" or "operated" inside the machine. These phenomena and concepts will have certain properties in the domain and since we want the system-to-be to faithfully operate that part of the domain, these properties become requirements on the system-to-be. For example, if you observe in the domain that an artwork always has at least one artist as its creator and you decide that the concepts of artwork, artist, and creating will be simulated by your system-to-be, then you can derive a domain requirement like "the system must associate to every artwork the non-empty set of artists who are the creators of that piece".

In the requirements "must allow" is not as good as "must provide means to": one can always claim that "must allow" is satisfied: "It doesn't forbid it, so this requirement is satisfied." You might want to say "must provide means to".

For more information and examples go to the guidelines (2.2.3)

Temporary Score : 
Urgency - 4
Difficulty - 1

**Comment by AnthonyMed13** [comment]
The system-to-be must support a 4-player multiplayer mode, allowing users to connect and play in real-time.

The system-to-be must provide means to automatically match players for a game or allow players to invite others to join a private game.

The system-to-be must enforce the rules of dominoes, including valid tile placement, turn management, and scoring.

The system-to-be must provide real-time updates for all players, ensuring that each player's view reflects the current state of the game.

The system-to-be must handle player turns sequentially, notifying players when it is their turn and preventing actions outside their turn.

The system-to-be must calculate scores based on standard dominoes rules and display a leaderboard.

The system-to-be must provide user authentication to allow players to create accounts, and Leaderboards.

The system-to-be must provide means to create, join, and leave game rooms, with appropriate game room visibility and access control (private vs. public games).

The system-to-be must handle the save states of the board to ensure that the game can be continued.

**Comment by AnthonyMed13** [comment]
@JadiellMV Cuando puedas chequear los domain requirements

**Comment by JadiellMV** [comment]
> @JadiellMV Cuando puedas chequear los domain requirements

Looks good to me!

**Comment by AnthonyMed13** [comment]
@AngelCIICMorales Could you take a look at to the domain requirements and check that they are good.

**Comment by AngelCIICMorales** [comment]
LGTM.
