### ISSUE TITLE
[Lecture Topic Task] 4.5.6 Digging out and making the Rule Engine Explicit

### ISSUE THREAD

**Issue by nsfrontera** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#321]
This task connects to formalizing implicit gameplay rules discussed in the lecture on Making Implicit Concepts Explicit by transforming intuitive game mechanics into clear, programmable logic within the Rule Engine. The lecture highlighted how implicit systems often operate in the background, relying on experience and informal understanding, making it essential for developers to extract and codify these systems. By creating explicit rules for different game modes like Classic Dominoes, All Fives, and Draw Dominoes, the Rule Engine defines precise behaviors for move validation, scoring, and game state evaluation. This shift from implicit to explicit ensures consistent gameplay, supports dynamic adaptability across modes, and provides a scalable foundation for future enhancements, aligning computational precision with strategic depth in game design.

difficulty 2
urgency 4

**Comment by Keiven-Soto** [comment]
Great work!
