### ISSUE TITLE
 [UI Team] Basic Asset Creation: Game Board ♟

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#33]
Develop the game's board and coordinate to accord color and functionality of said board. The purpose is to not only create the space for which the game is played upon, but also create a framework for any changes on palette in the future.

Scoring:
Difficulty: 4
Urgency: 4

**Comment by frances-sepulveda** [comment]
This board will be the default board for when the game stats. It was handmade using Dotpic. 

![d7640372-00a8-4af6-bcd0-08df070e1dae](https://github.com/user-attachments/assets/f3e11543-b65b-4e73-b5e4-603ee7f6c85b)

**Comment by PinkSylvie** [comment]
Looks great but I'm concerned on it clashing with the color palette decided

**Comment by AngelCIICMorales** [comment]
Please let me know if you will edit the design based on @PinkSylvie's suggestion. If you don't have time, then it can be improved next milestone.

**Comment by frances-sepulveda** [comment]
Hello! We will leave it as it is for now. After implementation in milestone #2 we will make it more complementary! Thank you for the feedback!

**Comment by AngelCIICMorales** [comment]
LGTM.
