### ISSUE TITLE
[Lecture Topic Task] Value Objects

### ISSUE THREAD

**Issue by RicardoJRSs** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#332]
Add information on how value objects apply to the project according to the lectures

**Comment by RicardoJRSs** [comment]
4.11 Analysis of Value Objects in Multiplayer Dominoes

Value objects are essential design components that enable improved domain modeling in situations where characteristics are still vital but identity is not. Our project's clean architectural design approach is represented by a better, more resilient, adaptable, and more efficient domain model that we obtain by encapsulating these features within objects. The function and use of various design components are examined in this section.


Characteristics and Justification

Lack of Conceptual Identity:
Value objects represent descriptive aspects without needing identity.
For example, objects like TilePosition or Score do not need an identity since we focus on their value (that is the position on the board or the points a player currently has). Avoiding this identity, we can prevent unnecessary complexity and instead focus on the descriptive aspect of these objects. If we were to assign identity to these objects we risk adding an analytical overhead and damaging the model with complicating distinctions that would affect our aggregates and increasing the maintenance efforts for the project.


Attributes-Only Design for Descriptive Domain Elements:
Objects like TilePosition (the row and column on the board) and Score (points a player has) describe non-unique characteristics. These attributes play a crucial role in representing the stage of the game without adding an unnecessary identity, allowing an optimized handling within the aggregates. Furthermore treating these elements like value objects reduces coupling, enhances data integrity and a more simplified domain model.


Clean Architecture principles:

The use of value objects is based on clean architecture and maintains immutability, clear separation of responsibilities, and reducing dependencies across layers. This ensures that domain operations remain consistent, aligning with the principles of single responsibility and dependency inversion.

Immutability and Integrity:
Value objects such as Score and TilePosition are not modified, thereby safeguarding the integrity of the game state. immutability also supports a simplified state-management strategy in the GameState aggregate, as changes to components rely on instances rather than modifications, ensuring a clean architecture’s preference for predictable and maintainable code.

Composition and Use of Value Objects
Simple and Complex Value Objects:
In the Dominoes game range, value objects range from simple types, such as numeric scores and positions, to complex compositions like GameMove, which include attributes like TilePosition and references to entities such as Player. A concrete way of seeing this can be by the GameMove value object capturing a player’s action by aggregating values such as tile placement, position and timestamp, thus creating a cohesive representation of the move that doesn't need unique identification.


Application of Flyweight Pattern:
For optimization of memory usage, in particular the storing of repeated data (identical DominoTile values), the Flyweight pattern is very beneficial. For instance, each tile representing the [3][5] configuration can share a single instance, therefore reducing the memory and supporting scalability.
Avoidance of Bi-directional Associations:
 By design, value objects avoid bi-directional associations since they lack identity, therefore having no need to reference the object that uses them. This reduces complexity in the domain model and allows entities like Player or GameRoom to manage relational behavior. If an object does need bi-directional association, indicates a need for identity and should be re-evaluated as a potential entity.
Practical Applications
Score and Tiles Positions as Value Objects:
The Score and TilePosition encapsulate essential attributes that describe data without an identity. They are passed by value, copied freely and don't retain any mutable state. 
Role of Value Objects in Aggregates:
In the GameRoom and Player aggregates, value objects contribute to data integrity and encapsulation. A Player aggregate may contain a Score value object, encapsulating the player’s score without any unique identification needed. In a similar way, the GameRoom uses TilePosition to manage its board state, thereby ensuring immutability and preventing inadvertent modifications.
Design Considerations and Trade-offs
Copying vs. Sharing:
Even though value objects are typically copied rather than shared, strategic sharing may be beneficial in memory-sensitive contexts. For example, using a shared instance for each unique tile configuration (e.g., all [3|5] tiles) reduces the object count and conserves memory without affecting gameplay. However, copying remains beneficial in scenarios where independence is needed, such as in TilePosition instances, where unique placements on the board necessitate separate copies for each tile’s coordinates.
When Mutability is Favorable:
Although immutability is a primary guideline, certain performance-sensitive cases may benefit from mutable value objects. If frequent changes to a value (such as an in-game Score that updates per move) become performance bottlenecks, a mutable, non-shared implementation may be more efficient. This decision should consider the environment; in distributed systems, for instance, immutable objects help avoid costly communication overhead from updating shared values.
Distinguishing Entities from Value Objects:
The Dominoes project’s strict adherence to differentiating entities from value objects ensures clean, efficient design. Entities such as Player and GameRoom are distinguished by unique identity, whereas value objects like Score and TilePosition remain attribute-based, minimizing unnecessary complexity and focusing each object on its primary role in the domain.

**Comment by AngelCIICMorales** [comment]
LGTM
