### ISSUE TITLE
Editing the style of the homepage to match the other game's parts

### ISSUE THREAD

**Issue by Joaquin939** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#337]
In this issue I will work on correcting the style of the components of the homepage to match the aesthetic we want to achieve for this game. Changing the fonts and colors of a few components

Difficulty: 5
Urgency: 4

**Comment by Keiven-Soto** [comment]
Hello, 20pts for changing the font and colors of components seems a bit exscesive. Unless the task becomes more complicated, 15pts seems more reasonable. The task points will be reduced to 15pts for now.
