### ISSUE TITLE
[UI Team] Basic Asset Creation: Placeholder Avatar Design 👩‍🎤

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#34]
In accordance with the basics of assets for our domino game, it is imperative to create placeholder avatar designs that can be built upon later on in other milestones. The main goal will be defined to create a framework for avatars and stack upon that. More details will be commented on soon.

Scoring:
Difficulty: 4
Urgency: 4

**Comment by PinkSylvie** [comment]
Saw the avatars in the google drive and they look great! Tiny detail tho to lean a small bit on following the color palette sent in the UI/UX team chat, if possible. Other than that everything looks great!

**Comment by AngelCIICMorales** [comment]
Please add the images in the request. It facilitates the review process.

**Comment by AngelCIICMorales** [comment]
Also let me know if you are going to edit the design based on the feedback from @PinkSylvie. If not, then I'll review the current design.

**Comment by frances-sepulveda** [comment]
@AngelCIICMorales They will stay how they are. If it does not match, then it will be fixed on milestone #2. 
![IMG_0170](https://github.com/user-attachments/assets/959bc7c2-862d-4556-a1cd-176036e633c8)
![IMG_0171](https://github.com/user-attachments/assets/f6f15128-7db2-4d68-8ba9-f71f199bad1d)
![IMG_0172](https://github.com/user-attachments/assets/fb6bafde-9b8b-4769-be1b-7f74fcec7504)
![IMG_0173](https://github.com/user-attachments/assets/eedea735-360c-4a92-87c7-1d6f348a655e)

**Comment by AngelCIICMorales** [comment]
I like it!
