### ISSUE TITLE
[Ul Team] design dominoes tiles 

### ISSUE THREAD

**Issue by Saul-Caban-UPRM** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#35]
Design a unique dominoes tiles set by drawing it by hand so we can use custom designs and not pulled from the web. Below I include a sample image. 
Difficulty: 4
Urgency: 3
![IMG_0261](https://github.com/user-attachments/assets/3cbf5d76-3736-4d39-a8db-0370a3cb766d)
![IMG_0227](https://github.com/user-attachments/assets/5b17e007-4197-4bd3-ad56-35717342f11c)

**Comment by AngelCIICMorales** [comment]
Please add a score.

**Comment by Saul-Caban-UPRM** [comment]
I've edited the original post adding a score.

**Comment by AngelCIICMorales** [comment]
Looks great!
