### ISSUE TITLE
[Lecture Topic Task] Making Implicit Concepts Explicit for UI/UX 🧤

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#359]
This task focuses on identifying, refining, and explicitly modeling implicit domain concepts that may not initially appear evident. The goal is to improve the clarity, coherence, and adaptability of the model by listening to domain language, scrutinizing design awkwardness, and recognizing overlooked yet crucial domain knowledge.

Through this task, we will analyze language used by team members and domain experts, identify concepts that influence functionality, and address areas in the design that feel unnatural or overly complex. This process involves reviewing team discussions, documentation, and existing code structure to bring implicit ideas into the explicit model. As a result, we aim to refine our project's design, reduce complexity, and ensure the model aligns with both the users’ and developers' understanding of the domain.

Task Objectives:

a. Identify Implicit Concepts: Analyze current project discussions, documentation, and code to detect any underlying domain concepts that may not be explicitly modeled.
Refine and Model: Transform these implicit ideas into explicit concepts within the model, ensuring clarity and alignment with project goals.
b. Validate with Domain Experts: Confirm with domain experts or team members to validate the relevance and utility of the newly articulated concepts.
c. Document Changes: Suggest updates to model diagrams, documentation, and terminology to reflect the refined understanding of the domain.

This supports building a more robust and maintainable model, fostering a shared understanding among all team members, and ensuring that the model evolves in response to insights gained from both the development and user experience perspectives.

Scoring
Urgency: 3
Difficulty: 3

**Comment by rukitoyordan** [comment]
### Suggested Approach:
**Domain Language Analysis and Stakeholder Insights Collection:**

Look for culturally specific terminology or phrases that may unearth domain concepts hiding in interviews and documentation. For example, detecting phrases such as "update of the game status," "validate tile placement," and "update of a leaderboard" would potentially indicate important features required to represent a face-to-face game.
Explore more colloquialisms or constructs particular to the Puerto Rican dominoes culture where users may familiarize with them implicitly but which are not yet represented in a manner that engenders an authentic cultural experience on the platform.

**Comment by rukitoyordan** [comment]
**Develop Ideas from Cultural and Societal Learnings:**

Explicit a Puerto Rican experience and cultural inclusion. Instead of making these elements stylistic choices, think of them as primary modeled features that shape the way people play the game and interact with it. Since it's really M3 now, then suggesting developing what we call "culturally themed customization" to solve for players' optionality (avatars, game boards, and in-game music) that represent their cultural heritage would help a ton. It would allow devs and future handlers to integrate those as part of the experience, rather than additional elements that do not fit with the game itself.

**Comment by rukitoyordan** [comment]
**Beat Around the Bush and Go Straight to Making it Explicit:**

Go over user interaction design, like creating joining rooms with specified traits. The project would help simplify complex workflows with clear modeling of the roles & interactions for Game Room Creation and Joining for Dominos Matches.
Implicit in the term "multiplayer engagement" is that some players will treat an experience as casual and others as competitive. A solution to this is to build separate models for both, creating a ruleset (somwhat to Ranked and Casual play with tiers) for casual play and another one for the competitive scene. That could mean explicitly differentiating between the system running in delete and clear conditions, which I suspect would better match user expectations and behavior imo.

**Comment by rukitoyordan** [comment]
**Be Explicit in Your Model Constraints and Behaviors:**

Set limitations around the real-time updates and sync needs as these are essential for providing a near seamless multiplayer experience in the dominoes. It follows that constraints such as "real-time sync of game states" need to be documented in a formal manner, for example, one player performing action X or Y should be reflected on other players' instances of the game in real time, if that makes sense.

Give explicit concepts to leaderboard fittings and "leaderboard visibility options" such that it adheres closely with the casual vs. competitive play as mentioned above. One example would be that leaderboard updates could be turned into a separate process that indicates live rankings to help control the competitive aspects of gameplay.

**Comment by rukitoyordan** [comment]
**Potential Benefits:**

In clarifying these implicit concepts, we are accomplishing not only cultural authenticity into the Multiplayer Dominoes platform but also user-centered design that supports intuitive gameplay and social interaction. This will help in understanding all aspects of team roles such as design, development, and testing benefits from this but also improves the quality and reality of the game.

Please let me know if this looks okay and if maybe can be implemented within a section on the Documentation as well for M3!

**Comment by AngelCIICMorales** [comment]
LGTM

**Comment by AngelCIICMorales** [comment]
I have raised the points for this task to 8.
