### ISSUE TITLE
[UI TEAM] Creating Wireframe

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#36]
**Description:**

- Create a distinct wireframe for the landing page and the sign up of the website. This individualized approach allows for diverse design perspectives. This task helps define the website's structure and layout. In case you are not familiar with wireframing, I will leave a few resources and examples attached here. 

**Deadline:**

- Aim to complete this task by September 5.

**Score:** 15 pts.

**Platform Suggestions:**

1. [Balsamiq](https://balsamiq.com/): Known for its simplicity, Balsamiq is a user-friendly tool that allows for quick and effective wireframing.
2. [Axure RP](https://www.axure.com/): Axure RP is a powerful tool that enables not only wireframing but also prototyping, making it a comprehensive solution for your design needs.
3. [Sketch](https://www.sketch.com/): Popular among designers, Sketch offers a flexible platform for wireframing and designing interfaces.
4. [Adobe XD](https://www.adobe.com/products/xd.html): Adobe XD provides a seamless design and prototyping experience, making it an excellent choice for creating wireframes.
5. [Wireframe.cc](https://wireframe.cc/): A straightforward and easy-to-use online tool, Wireframe.cc focuses on the essentials, allowing you to quickly sketch out your ideas. 
6. [InVision](https://www.invisionapp.com/): InVision not only facilitates wireframing but also offers collaboration and prototyping features for a more holistic design process.

**Resources:**

- [Wireframing Basics (Butter Academy)](https://www.youtube.com/watch?v=6t_dYhXyYjI&ab_channel=ButterAcademy): Guide to understanding the fundamentals of wireframing.

- [Figma Wireframing (CareerFoundry)](https://www.youtube.com/watch?v=qpH7-KFWZRI&ab_channel=CareerFoundry): Wireframing basics in Figma. Gain insights into key concepts and best practices.

**Examples**
![image](https://github.com/user-attachments/assets/1296d075-250f-4606-994b-d2910d6da537)
![image](https://github.com/user-attachments/assets/706934f8-97ed-48b1-8afc-ebd13c134fbe)

**Comment by AngelCIICMorales** [comment]
Please add a score.

**Comment by Adriana-Isabel** [comment]
![Screenshot 2024-09-04 232247](https://github.com/user-attachments/assets/3f5e860e-e247-49b3-99bb-63e1f61e241b)
![Screenshot 2024-09-04 232303](https://github.com/user-attachments/assets/6fa940e6-014b-4ef4-8c39-58dd2a0c3b42)

**Comment by Adriana-Isabel** [comment]
This wireframe shows a simple outline. If there is anything that could be added or moved, please let me know.

**Comment by AngelCIICMorales** [comment]
Please let your team leader and a manager know before closing a task.
