### ISSUE TITLE
[Lecture Topic Task] Give 5 Levels of Ignorance for the Database and User Authentication

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#360]
Expand the Levels of Ignorance with more concrete examples from the Database. This task needs to have accurate descriptions for each of the levels, and examples on how did this impact the current project.

Temporary Points:
Urgency: 4
Difficulty: 2

**Comment by AnthonyMed13** [comment]
Expanding on the themes of the Five Levels of Ignorance mentioned above here is a look at how each level affected the process of making the backend and how they were resolved. This was something very important to understand and it helped streamline the process of developing.

Zeroth Order Ignorance: 
We were confident in our ability to design a basic backend and we knew some of the requirements that we would need. Some of these were a schema with at least a username, email and password. We also knew we needed to make ways for the frontend to access the login and register routes.

First Order Ignorance: 
The team needed more research in recognizing additional components of the User’s schema, since we were not sure if we would want achievements to be added later down the line or other features related to the multiplayer connection system. By realizing this we could take steps to reinforce these small gaps in our knowledge.

Second Order Ignorance:
There were some issues that were unexpected and in between those one of them was the validation of JWT secret key for the login and sign in. It took awhile for us to realize that it was not using a random secret key but the default set one which was a major risk in the security of the user’s account. By adding additional debugging we are able to spot problems like this one with higher frequency.

Third Order Ignorance:
The team had bad ways  to demonstrate that drastic changes were done in the backend that required the need of additional instructions; this led to developers ineffectively researching on why something was failing now when in the past it was working fine. By bringing more up to date documentation and explanations on tasks needed to be done before the execution of the project we were able to reduce the amount of problems caused by this. 

Fourth Order Ignorance:
At the beginning before we learned about the levels of Ignorance there were times that pull requests were allowed to be merged without the person who allowed it fully understanding the code changes that were committed. This could have led to problems in the future with identifying bugs. Now that we are all informed we can take better measures to ensure that we request reviews from developers more accustomed to that part of the code.

**Comment by AnthonyMed13** [comment]
@AngelCIICMorales @ebrain-mendoza121 if you could check this to ensure it's okay to close the issue

**Comment by Keiven-Soto** [comment]
Could you provide me a link to the section of this LTT. I could not find it in the milestone 3 doc

**Comment by AnthonyMed13** [comment]
> Could you provide me a link to the section of this LTT. I could not find it in the milestone 3 doc

This was a topic mentioned in class beforehand not necessarily from milestone 3

**Comment by Keiven-Soto** [comment]
What section in the documentation did you added this?

**Comment by AnthonyMed13** [comment]
@Keiven-Soto i haven't added it yet I always send it here first to get it approved and the issue closed then I add it to the documentation

**Comment by Keiven-Soto** [comment]
good work
