### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Needs

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#363]
Please fix the section according to the following critique from the professor:

That text starting at "beyond just coding" is valid, but it's not placed well. Here you could talk about that there is a need to understand your domain (that, of course, is rather obvious, so maybe you could motivate some specific area in which more understanding is needed in particular). You say "as we design the platform, we ensure that our sketches and plans align with..." You describe what you do, but this is the section on the needs, so you should talk about those. For example, "motivated by our goal to create a user-friendly and relevant experience, we NEED to understand the requirements of our target audience and we NEED to ensure that the sketches and plans remain aligned to these requirements" (of course you do not need to capitalize...). Here we are merely capturing needs, we are intentionally not talking about how we think we should meet these needs. In the section on your ideas, you can then talk about how, for example, you intend to get a good understanding of the requirements of your target audience, or how you intend to ensure that your sketches and plans remain aligned to them.

**Comment by ebrain-mendoza121** [comment]
When documentaion opens this is what to be added: 

There is a clear need to thoroughly understand the domain of online multiplayer dominoes to create a platform that resonates with our target audience. This includes recognizing the characteristics of user experience in online gaming environments, especially in a game with strong social and traditional roots like dominoes. Specifically, we need details of the expectations and gameplay preferences of our users, which may include both experienced players and newcomers who may need guidance on standard rules, game objectives, and gameplay flow. 
Motivated by our goal to create a user-friendly and relevant experience, we need to identify and address key requirements of our target audience. These include the need for clear, accessible game instructions, real-time play to maintain engagement, and an intuitive interface that allows players to navigate the platform with ease. Additionally, we need to design features that promote social interaction, as players often seek a sense of community and friendly competition in multiplayer games. This may involve providing chat options, or leaderboards. Another critical need is continuous feedback from users, which will help us stay attuned to their evolving preferences and quickly identify areas for improvement. This feedback loop will be crucial in refining and enhancing the platform over time, ensuring it remains responsive to user expectations.
