### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Synopsis

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#364]
Please fix the section according to the following critique from the professor:

Your synopsis is still not including all the different work that the project has to do. For example, it's not talking about requirements engineering. In general, you want to synopsis to tell a person who does not read anything else of the document, what the project aims to achieve, but also what the project already knows they will have to do. So, since you already know that you have to do domain engineering, that work should be mentioned and detailed (somewhat) here. Of course, you would not go into the fine detail, but imagine you want to get funded by someone: if you put all the detail here, they might just stop reading, but if you leave out important parts of the work that you have to do or you fail to communicate the extent of the work, they will not give you all the funds that you will need to succeed.

**Comment by FrancesC8** [comment]
@PinkSylvie @AngelCIICMorales I modified and added contents to the `1.3.2 Synopsis` in the [documentation](https://docs.google.com/document/d/16JWl_dXbHArb5V8-UmIO0Z7dAHTrwcfmdk2KTgEJo9c/edit). Please review.
