### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Stakeholder Interviews

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#366]
Please fix the section according to the following critique from the professor:

The new text after the stakeholder interviews analyzes their responses and should therefore go into the analytic part.

**Comment by sandy-marrero** [comment]
Made changes to M3 documentation document
[Documentation Link](https://docs.google.com/document/d/16JWl_dXbHArb5V8-UmIO0Z7dAHTrwcfmdk2KTgEJo9c/edit?tab=t.0#heading=h.hulbro50t2es)
