### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Remove and Fix Accordingly

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#367]
Please fix the section according to the following critique from the professor:

You do not need (or even want) a separate section on the relationship between the domain rough sketch and the terminology. This point on the guidelines is only there because very many students seem to forget that there is a specific way by which we get from the domain rough sketch to the domain terminology. I suggest you review this…

**Comment by sandy-marrero** [comment]
Made changes to address feedback in documentation.
[Documentation Link](https://docs.google.com/document/d/16JWl_dXbHArb5V8-UmIO0Z7dAHTrwcfmdk2KTgEJo9c/edit?tab=t.0#heading=h.c96dq4ttuo34)
