### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Narrative

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#368]
Please fix the section according to the following critique from the professor:

 The narrative still is not what we need to see here. What yours talks about is a background to your project, but that's NOT what the domain narrative's purpose is. It's purpose is to narrate the domain. For example, in your domain the narrative could say things like "each player as a collection of tiles, their "hand". At the start of the game they draw an initial hand from the lot of domino tiles. The player can see the tiles, but the other players cannot. The only way to discard of tiles from a player's hand is by playing them to the middle of the table. Except for the first tile, tiles can only be played by matching them to tiles that have previously been played... Players take turns playing tiles. In each turn a player can play at most one tile. Etc. etc." The main point here is not whether I got the rules right (I might not have), but that the narration tells a story about how the concepts of the domain of dominoes hang together. Also observe that all these things like "family encouragement", where the game is played, or whether players need to concentrate does not matter for the domain narrative (it might be helpful elsewhere).

Scoring: 
Difficulty: 2
Urgency: 4

**Comment by rukitoyordan** [comment]
@frances-sepulveda and I were working on this in the past weekend or so, but managed to finally send this in after we got out of exams for the week. We will be sending out the rest of our tasks today. For this specific portion, I decided that reinventing the whole text except probably the third paragraph that was in the original 2.1.4 Narrative portion actually portrayed the narration of the domain and telling a story with rules in mind and how the domain concepts are connected.

**Comment by rukitoyordan** [comment]
> In dominoes, each player gets a "hand" consisting of several randomly drawn tiles from a set that has been shuffled. The tiles are rectangular pieces that are divided into two square ends with numbers of pips, usually from 0 to 6, and players keep the pips hidden from one another. Within this context, the player is expected to throw the dominoes all by himself on the board.

> The very first domino placed at the beginning of the game is the so-called double tile at the center of the board. Players take turns in laying tiles along the exposed ends of previously played tiles in order to extend a chain of tiles on the board. To play a turn, a player must select from among the proper tiles and, in the lack of any in his/her hand, draw from the pool until a tile is biblically correct, or the drawing pool is emptied.

> This is a game of strategy and foresight. It calls for anticipating the moves of opponents, remembering which tiles have been already played, and calculating the probabilities for the players to increase the chances of winning the game. Much of the success depends on when and where the player decides to play, as well and how others are blocked from completing their moves. A round ends when one player places his last tile, thus winning that round. Alternatively, if none of the players can make a valid turn because there is "blockage", then the winning player becomes that with the least number of pips remaining in his hand.

> There are various rule sets that add much more depth and variety to the game. For example, in the game of "All Fives," players score points when the open ends of the layout sum to a multiple of five. Similarly, in the game of "Draw Dominoes," rounds contribute to total scores, with the first player to reach a specified score winning. These variants ensure that the game can be adjusted to suit the different needs and customs of players. 

> The board gradually changes through the game by adding tiles to it, molding a collective visual of the game state. A scoreboard keeps track of points scored by each player, updating itself in real-time as per the rules currently in force. Simple mechanics blend seamlessly with a deep strategy in dominoes. The two features make this board game exciting for both casual and serious players. Hidden information, calculated risks, and the gradual unfolding of the game's state form an essence of this great classic.
>

**Comment by rukitoyordan** [comment]
Above is exactly what was added in section 2.1.4 Narrative, please let us know if it aligns with fixing this based on the professor's critiques or not!
