### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Events and Behaviors

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#369]
Please fix the section according to the following critique from the professor:

In the account registration process you state that "a user submits their registration form in the app" is an event. You most likely mean something else: that the action of submitting triggers an event, for example. Think about this carefully: "submitting" has an actor, a submitter and "submitting" has duration. Both are strong hints that "submitting" is an action and not an event. So, if you're on the lookout for a related event, then you could ask "what's the event that ends the submitting?". Of course, you could just answer "the user has just submitted..." or alternatively "the registration form has just been received". Again, consider that event's qualities: to submit takes an actor, but as soon as the form has been submitted, that moment in time, that end of the submitting, that does not need the actor. Also, it has no duration. Both are hints that this is an event.

A behavior has several actions that are executed in sequence and that are separated by events. The events and the behaviors must be meaningful for the domain. That is, it does not make sense to just further and further decompose actions just for the sake of decomposing them. Instead, if there are actions and events within some operation and these in turn are from the domain, then the operation is a behavior. We may even have several views: if we want to take a high-level perspective, then we do not consider the component actions and events and therefore the operation becomes an action, but if we do care about the detail, then we show the component actions and events and the operation becomes a behavior. The format that you use, where you use the "behavior" just for the description, but not to show the steps and the events in between, that's not what we need to see here.

**Comment by RicardoJRSs** [comment]
Account Registration Process
Behavior: The system facilitates the process of creating a new account, enabling the user to join the domino-playing community. This behavior involves verifying the user's information, creating an account, and confirming their registration. This behavior reflects the system facilitating the user’s entry into the dominoes-playing community. It’s not just about creating an account, it’s about the user becoming part of a broader cultural tradition where dominoes are played. This behavior encompasses the entire process of joining the dominoes community, from signing up to logging in and getting ready to play. The steps are outlined below:
Action: A user fills out the registration form with their username, password, and email address and clicks the "Register" button.
Event: The system receives the completed registration form.
Action: The system validates the submitted information (e.g., checking for a unique username and valid email format).
Event: Validation completes, either successfully or with errors.
Action: If validation is successful, the system creates a new account in the database.
Event: The account is created and stored successfully.
Action: The system sends a verification email to the user with a link to confirm their registration.
Event: The verification email is dispatched.
Action: The user clicks the link in the verification email to confirm their account.
Event: The system marks the account as verified and grants the user access to the application.
Player Joins or Creates a Game
Behavior: The system supports players in joining an existing game or creating a new room, facilitating a social and competitive domino-playing environment.  The system supports the player in becoming part of a shared social experience. Whether joining a game that’s already in progress or creating a new room, the behavior here represents how the app facilitates the social and competitive nature of dominoes. In real life, this is like joining or setting up a dominoes game with friends or family. The behavior involves creating a space where players can strategize, bond, and participate in dominoes: 
Action: A player selects the option to join an existing room or create a new one.
Event: The system receives the player’s request.
Action: If the player chooses to create a new room:
The system prompts the player to configure the room settings (e.g., room name, privacy, game mode).
Event: The system receives the room configuration details.
The system generates a new room based on the provided settings.
Event: The new room is created and made available for others to join.
Action: If the player chooses to join an existing room:
The system displays a list of available rooms and validates the player’s selection (e.g., room availability, password for private rooms).
Event: The player is added to the selected room.
Action: The system updates the game room’s state to reflect the new player and sends a confirmation to the player.
Event: The player successfully enters the game lobby.
Game Start
Behavior: The system transitions the game from preparation to active gameplay. This behavior reflects how the system handles the transition from preparation to gameplay. In the context of dominoes, this is the moment when the social gathering transitions into focused competition, where strategy begins. The system mimics this behavior by preparing the game environment and setting up the match in a way that feels like the real-world dominoes game.
Action: All players indicate they are ready to start by clicking "Ready."
Event: The system marks all players as ready.
Action: A designated player clicks the "Start Game" button.
Event: The system receives the command to start the game.
Action: The system shuffles the dominoes, deals them to the players, and prepares the game board.
Event: The game board is initialized with shuffled tiles.
Action: The system selects the starting player based on the game mode’s rules.
Event: The first player is assigned, and their turn begins.
Domino Placement and Validation
Behavior: The system manages the gameplay dynamics by validating moves and updating the game board. This behavior represents the system's management of the game’s flow and the strategic depth of each player’s turn. Just like in real life, placing a domino isn’t only about matching numbers—it’s about strategy, memory, and anticipating opponents’ moves. The app captures the same behavior by not only validating the placement but also shifting the game’s progression. This mirrors how players mentally map out their next moves in real-world games.

Action: A player selects a domino tile and places it on the board.
Event: The system receives the player’s move.
Action: The system validates the placement according to game rules.
Event: Validation completes (either successful or failed).
Action: If the move is valid, the system updates the game board to reflect the new tile and progresses to the next player’s turn.
Event: The game state updates, and the next player's turn begins.
Action: If the move is invalid, the system prompts the player to try again.
Event: The player is notified of the invalid move.
Player Wins
Behavior: The system recognizes and finalizes the winning condition, providing closure to the game session. The behavior here reflects the culmination of strategic play. It mirrors the sense of achievement and closure that players experience in real-world domino games. In dominoes, winning is often the result of carefully planned moves, quick thinking, and anticipation of opponents' actions. The system acknowledges this by celebrating the winner and updating the results, creating a similar sense of satisfaction as in a real-life game.

Action: The system detects a winning condition (e.g., a player uses all tiles or has the fewest points in a blocked game).
Event: The winning condition is triggered.
Action: The system announces the winner and updates the leaderboard.
Event: The leaderboard reflects the new rankings.
Action: The system prompts players with options to start a new game or exit the lobby.
Event: Players receive the prompt for next steps.
Game Room Exit
Behavior: The system handles the player’s decision to leave the game room and ensures the session concludes cleanly if necessary. This behavior captures how the system handles the natural conclusion of a session, much like the end of a real dominoes game. If the last player leaves, the system closes the room, just as a dominoes game might end naturally when everyone finishes playing. The system mimics the real-world flow of players leaving a game, ensuring that the session is closed and all game data is cleaned up, allowing the experience to transition smoothly just like in a real-life setting.

Action: A player selects the "Leave Room" option.
Event: The system receives the leave request.
Action: The system removes the player from the room and updates the room’s state.
Event: The room status is updated to reflect the player’s departure.
Action: If the last player leaves, the system closes the room and cleans up game data.
Event: The room is closed and game data cleared.
Action: The system confirms the player’s exit and provides options to join another room or return to the main menu.
Event: The player receives confirmation and navigational options.

**Comment by RicardoJRSs** [comment]
Updated Events and Behaviors so that it aligned with the professors comment. Restructured the section like the professor said.

**Comment by Keiven-Soto** [comment]
good work!
