### ISSUE TITLE
[UI Team] Avatar Power-ups 🧑‍🎤

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#37]
This issue focuses on the creation of hand-designed power-ups that will unlock virtual currency for players, which can later be used to purchase different clothing options for their avatars. These power-ups are being crafted in a pixel art style using the app "Dotpic" and will be awarded after players reach specific milestones, such as consecutive wins or in-game achievements.

At this stage, the focus is on the design of these avatar power-ups, ensuring that they align with the overall style and gameplay. The successful design of these custom power-ups will provide a foundation for future integration, enhancing the player experience through personalized avatar customization.

Once completed, this design phase will set the stage for eventual implementation, bringing unique aesthetic rewards and adding depth to the multiplayer domino game.

Scoring:
Difficulty: 4
Urgency: 3

**Comment by frances-sepulveda** [comment]
This power-ups will be added to the avatars after a certain amount of winning streaks. They were handmade using dotpic. 

![6712a8e7-feb1-4b0d-bd63-e1727e9f6a92](https://github.com/user-attachments/assets/d5a0cb5e-397c-4daa-a81b-8094ab442ac0)
![77773618-2e84-441c-886f-31a22975f3ea](https://github.com/user-attachments/assets/b67e4193-948f-4e80-9699-eb463f29e6d5)
![a62217d4-b0ed-4e21-9723-e93a13956feb](https://github.com/user-attachments/assets/77ab3c9f-9b53-4c63-9505-13101f6ddf71)
![f5b9e8a5-fe8d-4bc7-ba81-a7ff7510923b](https://github.com/user-attachments/assets/c64fa2ba-f56e-42cb-81b4-db258beb16e5)

**Comment by AngelCIICMorales** [comment]
Looks great!
