### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Function Signatures

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#370]
Please fix the section according to the following critique from the professor:

Your function signatures are getting better! Much better! But they still need to go together with the actions that they describe. On the showPlayerChips function: if it's the domain function you're after that gets the players chips for them, as you write, whether or not players have an ID is really irrelevant. So, you could simplify and make this more "punchy" if you just make the function take a Player. From the domain model's perspective, you'd say "there's an operation by which a player can access/view their chips". The ID is really only a way to get to the player object, but the conceptually the operation uses the player. By the way, if you wanted to continue to use the player ID, you'd also have to pass in some kind of player repository, sense otherwise the function would have no way to actually resolve the player ID to a player object.

**Comment by sandy-marrero** [comment]
Hi, this one is a duplicate. Yesterday I updated one of my tasks to cover this to continue the fixes made in the previous milestone. 
- #312

**Comment by PinkSylvie** [comment]
> Hi, this one is a duplicate. Yesterday I updated one of my tasks to cover this to continue the fixes made in the previous milestone. 
> 
> - #312 

Thank you for clarifying the task has been closed.
