### ISSUE TITLE
[Documentation Fix] Fix Milestone 2 Issues with Documentation - Domain and Interface Requirements

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#371]
Please fix the section according to the following critique from the professor:

Many of the requirements that you list under "domain requirements" are much too broad to actually assign them just to one category. Take, for example, "The system must notify players when it is their turn." What all does it take to do this? From the perspective of the domain, there are players, there are turns, and in dominoes there's always to single player whose turn it is. So, as domain requirement we immediately get "the system must maintain which of the players has the turn." But we also get interface requirements, for example "the game UI must indicate for the player whose turn it is that it is their turn..." here you have to decide how this should happen, perhaps the tiles change color or perhaps you have some other way to indicate to the player have the turn that it is their turn. "The game UI must indicate for all the players who currently do not have the turn, who it is that does have the turn." Again, you'd have to decide how you want this to be represented. But in both cases we get interface requirements. The same thinking applies to e.g. the creation of game rooms. There are some aspects that belong to the domain and some that are interface requirement (and of course there are some that belong to the machine requirements even if I have not given an example here).

On the interface requirements "the system must generate a room password...". That's too broad as an interface requirement. There are, of course, interface aspects here, but there are also other aspects that are not interface requirements. This same thinking applies to many of the other interface requirement that you list.
 
Please also review the comments on the previous submission comments:

“Many of your domain requirements are too big, too broad to be assigned you just one category. For example, take "The system-to-be must calculate scores based on standard dominoes rules and display a leaderboard." there are domain aspects in this (e.g. that there have to be functions that calculate scores), but there are also other aspects in this. One would be the display of the leaderboard.

Your interface requirements also mix different aspects together and they're not stated as requirements on the system-to-be.”

**Comment by RicardoJRSs** [comment]
2.2.3 Domain Requirements 
The system must maintain and manage a 4-player multiplayer mode and a single-player mode.
The system must support real-time connections and synchronize the game state across all players in the room during multiplayer sessions.
The system must provide a mechanism for automatic matchmaking, pairing users into game rooms based on availability and rules.
The system must enable users to invite other players to join private games.
The system must enforce the rules of dominoes.
The system must validate tile placement.
The system must manage the player's turn.
The system must keep the scoring.
The system must manage the player turn order, ensuring sequential play.
The system must maintain the current state of the board, including placed tiles and open ends.
The system must validate tile placements and reject invalid moves according to game rules.
The system must calculate player scores based on standard dominoes rules.
The system must provide game-ending conditions based on the selected game mode.
The system must store and maintain the game state to allow for pausing and resuming gameplay without data loss or progression loss.
The system must track which player has the current turn.
The system must notify the current player when it is their turn and restrict all the other player moves except the current player ensuring fair and rule based play.
The system must provide real-time updates to all players based on the game’s state, this includes player’s turns, moves, and scores.
The system must maintain and update a leaderboard that displays player rankings based on wins, losses, and scores.
The system must calculate and award achievements to players based on specific milestones of the game, such as winning a game without drawing a tile.
The system must allow users to create, join, and leave game rooms.
The system must handle public and private rooms, including generating unique passwords for private rooms.
The system must ensure that game room configurations, such as maximum players and rule sets, are respected.
The system must provide user authentication.
2.2.4 Interface Requirements 
The system must display a landing page that allows users to either create a new account or log into an existing one, using distinct buttons labeled "Sign Up" and "Log In."
When creating an account, the system must present fields for the user to enter a username, password, and email address.
The system must validate user inputs for the sign-up process. For instance:
If the username is already taken, the system must display the error message: “Username already taken.”
If the email format is invalid, the system must display the error message: “Invalid email format.”
Upon successful registration, the system must automatically log the user in and redirect them to the home screen with a welcome message.


The system must prompt users to enter their username and password to log in.
If the credentials are invalid, the system must display the error message: “Incorrect username or password,” and allow the user to retry.
The system must allow up to three consecutive failed login attempts before locking the account temporarily, with a message: "Too many failed attempts. Please try again later."
The system must provide a "Forgot Password" option on the login screen.
Upon selecting this option, the system must prompt the user to enter their registered email address.
The system must send a password reset link to the provided email and display a confirmation message: “A password reset link has been sent to your email.”
The system must send a verification email upon account creation or password recovery.
The verification email must include a link to confirm the user's email address.
The system must prevent unverified accounts from accessing key features and display a notification: “Please verify your email to unlock full access.”
The system must allow users to update their profile information, such as their username, password, or email, via the "Account Settings" page.
The system must validate updated inputs and display error messages for invalid entries (e.g., "New email format is invalid").
The system must provide a form for creating game rooms with the following customizable options:
Room name.
Privacy setting (public or private).
Maximum number of players.
Game rules (e.g., scoring mode or tile draw rules).
The system must validate these settings and display an error message if any configuration is invalid (e.g., “Room name cannot exceed 20 characters”).


For private rooms, the system must generate a unique password and display it to the room creator.
The system must prompt users attempting to join a private room to enter the room password.
If the password is incorrect, the system must display an error message: “Incorrect password. Please try again.”
The system must display a directory of public game rooms, including:
Room name.
Current number of players.
Privacy status (e.g., "Public" or "Private").
The system must allow users to filter or search for rooms by name, number of players, or game settings.
Clicking the "Join" button must allow users to join public rooms directly or prompt them for a password if the room is private.
The system must display the player’s domino tiles and the game board when entering a game room.
The game board must update in real-time to reflect moves made by all players.
The system must enable players to interact with their domino tiles through drag-and-drop functionality to place tiles on valid positions on the board.
When a player attempts an invalid move, the system must provide immediate feedback, such as:
Highlighting the invalid tile in red.
Displaying an error message: “Invalid move. Please try again.”
The system must highlight the current player’s name and tiles when it is their turn.
The system must provide visual or textual cues to indicate whose turn it is for all players in the game room (e.g., displaying “It is Player X’s turn” above the board).
The system must provide a “Pause Game” button for players, accessible at all times during gameplay.
When the game is paused, the system must display a message: “Game is paused. Waiting for resume.”
Upon resuming, the system must prompt all players with a “Resume Game” button to continue.
The system must provide an in-game chat window for players in the same game room.
Users must be able to toggle the chat window open or closed during gameplay.
The system must notify players when a new message is received in the chat (e.g., “Player X: Good move!”).
The system must include a “Game Rules” button within the game interface.
Clicking this button must display a pop-up with the rules for the current game mode.
The system must display notifications when players earn achievements (e.g., “Achievement Unlocked: First Win!”).
The system must maintain a record of unlocked achievements on the player’s profile page.
The system must display a leaderboard at the end of each game, ranking players by their wins, losses, and scores.
The leaderboard must update dynamically to reflect the current game state.
The system must allow users to view their overall rankings from the main menu or their profile page.

**Comment by RicardoJRSs** [comment]
I fixed documentation according to the professor and specified the requirements according to the domain

**Comment by Keiven-Soto** [comment]
Great work
