### ISSUE TITLE
[Lecture Topic Task] [Documentation Fix] Fix Milestone 2 Issues with Documentation - Factories

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#374]
Please fix the section according to the following critique from the professor:

On the sequence diagram on page 61, if the user wants to make a selection of the game modes, then the list of available game modes would have to reach the user before they make that selection. So, game state would have to forward that list to the user.

**Comment by FrancesC8** [comment]
The diagram that the professor was referring to was the sequence diagram from section `4.4 Factories`. I updated it with the professor's feedback. 

@AngelCIICMorales @ebrain-mendoza121 please review the sequence diagram in section `4.4 Factories` in the [documentation](https://docs.google.com/document/d/16JWl_dXbHArb5V8-UmIO0Z7dAHTrwcfmdk2KTgEJo9c/edit?usp=sharing)
