### ISSUE TITLE
[Lecture Topic Task] [Documentation Fix] Fix Milestone 2 Issues with Documentation - Supple Design

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#375]
Please fix the section according to the following critique from the professor:

The way you use supple design is not the way it's normally understood. Supple design is a design that you arrive at after many iterations of refining and refactoring the design. Then it becomes supple, meaning that e.g. new requirements no longer lead to deep rearrangements. So, you could, for example, talk about why you believe that your design after so many iterations has become supple, showing how newly identified requirements can easily be integrated.

**Comment by print-Eruki** [comment]
Completed this issue, changes can be found on sections 3.3 and 4.10.
![image](https://github.com/user-attachments/assets/563bfaad-c6ce-4fed-88f9-46448a7221d6)
I added support information to the 3.3 so that 4.10 make more sense! 
@Keiven-Soto @AngelCIICMorales @ebrain-mendoza121
