### ISSUE TITLE
[Lecture Topic Task] Repository Design Pattern Implementation Diagram 

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#378]
Create a repository Design Pattern diagram to demonstrate how our project implements the aforementioned design pattern in the documentation. 

- Create a diagram with all of the entitys (domains and aspect) and their respective relationships
- Added to the documentation

**Comment by print-Eruki** [comment]
![image](https://github.com/user-attachments/assets/72751f24-8881-4ca8-b075-64d7f6200f37)
Created the diagram, and added to section 2.3.4. ready for review

@Keiven-Soto @ebrain-mendoza121 @AngelCIICMorales

**Comment by Keiven-Soto** [comment]
good work
