### ISSUE TITLE
[UI Team] Board Power-Ups 🀹

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#38]
This issue addresses the creation and design of alternative game boards, which will be unlocked as power-ups for players who achieve a certain streak of consecutive wins. These custom boards were handcrafted in the app "Dotpic" and include three different designs in addition to the standard board.

The successful integration of these game boards will allow players to select and use them as rewards for their winning streaks. This implementation from GameState team will be essential for visualizing the unique layouts, testing their functionalities, and ensuring compatibility with core game mechanics 

This enhancement will not only enrich the player's experience but also pave the way for future customizations and optimizations, offering more variety and engaging incentives for players in the multiplayer domino game.

Scoring:
Difficulty: 4
Urgency: 3

**Comment by frances-sepulveda** [comment]
This boards will be unlock after a certain amount of streaks or money gain from winning. 

![IMG_0176](https://github.com/user-attachments/assets/0d1744e2-d072-4eda-9b80-ca91c0b25a48)
![IMG_0177](https://github.com/user-attachments/assets/5b645077-c666-48aa-8136-6c64548a2fa7)
![IMG_1183](https://github.com/user-attachments/assets/3f839c31-b140-4ba6-91e7-5f53c86952e0)

**Comment by PinkSylvie** [comment]
I like how they look! I'm a bit worried if the tiles could get lost on the board while the players play, unless the tiles contrast enough with the board so that doesn't happen.

**Comment by PinkSylvie** [comment]
@AngelCIICMorales @Keiven-Soto

**Comment by frances-sepulveda** [comment]
@PinkSylvie Thank you for the feedback! We have two plans for that; one is to make them "float" on the board and the second one is to make tiles specifically for each board after having a certain amount of streaks which would be the best idea to complement them.

**Comment by PinkSylvie** [comment]
What would be the default board then?

**Comment by frances-sepulveda** [comment]
It was created in a different ticket since that one is the main board, this are just "power-ups" based on streaks.

**Comment by AngelCIICMorales** [comment]
I love these designs! Good work.
