### ISSUE TITLE
Design Dynamic Avatar Frames Based on Winning Streaks

### ISSUE THREAD

**Issue by igrv2003** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#39]
To enhance player engagement and visually reward achievements, this task will focus on designing dynamic avatar frames that reflect players' winning streaks within the game. These frames will visually upgrade around player avatars in profile and game settings, providing immediate recognition and incentive for continued play. 

The frames could be tiered like this:
Bronze Frame: For players with a winning streak of 5-9 games.
Silver Frame: For players with a winning streak of 10-24 games.
Gold Frame: For players with a winning streak of 25+ games.

Each frame design should integrate with the basic avatar designs being developed in #34 and should consider the user interface requirements set out in #37 .

Scoring:
Difficulty: 3
Urgency: 3

**Comment by igrv2003** [comment]
### [Link to Figma Page](https://www.figma.com/design/9tB7x524EnEF8I57CyxoMg/Colors%2C-Defaults%2C-Screens?node-id=41-8&t=L18H6NnsekZRVGxw-1)


### Model

![Image](https://github.com/user-attachments/assets/957ab81b-378a-4171-8e8b-cb53d8165669)


### Avatar Frames
![Image](https://github.com/user-attachments/assets/be7fbe19-034d-45cf-b267-d140e2e39dff)

**Comment by PinkSylvie** [comment]
I think it looks great! Make sure to make each avatar frame into a transparent .png image and add the images to the project shared folder for easy access to whoever implements the avatar frame designs into the webapp. After you do that it would be ready to close in my opinion.

**Comment by igrv2003** [comment]
Done. I added the frames to the project's shared folder. [[Link]](https://drive.google.com/drive/folders/1V_WXiG0jRv5vUQYuCSBcd2AF4E2ODZBO?usp=drive_link)
