### ISSUE TITLE
[Lecture Topic Task] Refactor functions in sign up and login to use Dependency Injection design pattern

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#390]
Functions in our current implementation have direct dependency to other functions, we can refactor the functions to instead inject the dependency to make unit test far easier to implement and easier to integrate with other design patterns. See example [here](https://www.youtube.com/watch?v=J1f5b4vcxCQ&pp=ygUUZGVwZW5kZW5jeSBpbmplY3Rpb24%3D).

**Comment by Negroni1** [comment]
Example of dependency injection:
![image](https://github.com/user-attachments/assets/cbdb5c36-85d5-44ff-b2de-7f65546c7744)
