### ISSUE TITLE
In-Game Overlays for Game Events

### ISSUE THREAD

**Issue by igrv2003** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#40]
This task involves creating overlays to enhance player interactions during critical moments in the game. The overlays will focus on three key scenarios:

- **Player Turn Notification:** Design an overlay that notifies players clearly when it's their turn.
- **Victory Announcements:** Create celebratory or supportive overlay for game victory.
- **Loss Announcements:** Create an overlay for when any player looses a game. 

Scoring:
Difficulty: 5
Urgency: 3

**Comment by igrv2003** [comment]
### [Link to Figma Page](https://www.figma.com/design/9tB7x524EnEF8I57CyxoMg/Colors%2C-Defaults%2C-Screens?node-id=59-16&t=RdvO5kQNc4TKVEyB-1)

### [Link to Project's Shared Folder](https://drive.google.com/drive/folders/1dDiPys5bB0gkhg5OIbtMzh1ZN2M7g-yf?usp=drive_link)

![Image](https://github.com/user-attachments/assets/16d52980-7c89-4301-b633-742f85ccba9a)

![Image](https://github.com/user-attachments/assets/0e775c56-ead8-4789-b737-4925fbfcce78)

![Image](https://github.com/user-attachments/assets/c5136fc3-2c30-45a8-b100-8572994addaa)

**Comment by PinkSylvie** [comment]
I think it looks great! Would be nice if it match with the colors used in tasks #60 and #5. I'm worried that the dark could maybe get lost in the already dark colors planned in the mock up task #60

**Comment by igrv2003** [comment]
Here are the new overlays with the specified color palette.

![Image](https://github.com/user-attachments/assets/836b6d99-b43c-4e13-a345-2e5cf7e3bb72)

**Comment by PinkSylvie** [comment]
It looks great! @AngelCIICMorales @Keiven-Soto what do you think?

**Comment by AngelCIICMorales** [comment]
I love it! Good work.
