### ISSUE TITLE
[Lecture Topic Task] 4.14.5 Observer Pattern

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#403]
Points: 8pts.

**Comment by Adriana-Isabel** [comment]
In the Domino project, the Strategy Pattern is used to manage the decision-making processes for both bots and human players. The design allows the behavior of players to be encapsulated into interchangeable strategies, providing flexibility in gameplay. Each player object contains a reference to a MoveStrategy interface, which defines the behavior for selecting the next move during their turn. This abstraction allows for multiple strategies to coexist and enables dynamic switching of strategies as the game progresses.
For example, bot players may adopt an Aggressive Strategy to prioritize moves that maximize points or play tiles with high values, while a Defensive Strategy might focus on blocking an opponent's potential moves or minimizing their scoring opportunities. There is also a Random Strategy for unpredictable behavior, where moves are selected without clear prioritization. This randomness adds an element of surprise, particularly in beginner modes or casual matches. For human players, the strategy might default to manual selection, allowing them to choose moves based on their intuition. However, they could also opt to receive suggestions based on an AI-driven strategy, such as highlighting the most optimal move based on game state analysis. In competitive modes, bots may even dynamically switch strategies during gameplay—for instance, transitioning from defensive to aggressive when falling behind in points. By factoring decision-making logic into separate strategy classes, the pattern simplifies the main game logic, making it easier to maintain and extend. For instance, adding a new strategy, such as one optimized for minimizing the number of tiles left, would only involve implementing the MoveStrategy interface without modifying the core game. This design ensures scalability and adaptability, essential for maintaining a rich and engaging gameplay experience.

**Comment by Adriana-Isabel** [comment]
@AngelCIICMorales @Keiven-Soto I finished all of my LTTs.

**Comment by Keiven-Soto** [comment]
Once again, great work!

**Comment by Adriana-Isabel** [comment]
@Keiven-Soto I updated the issue.
