### ISSUE TITLE
[Lecture Topic Task] Composite Pattern

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#404]
Implement the Composite pattern to model shipment routes hierarchically. This will allow uniform operations on both composite routes and individual route legs, improving traversal and simplifying route management.

Points: 8pts.

**Comment by Adriana-Isabel** [comment]
In the Domino project, the Composite Pattern is utilized to represent the game's structure, specifically the tiles and their placement on the board. The board itself is modeled as a composite structure, where each Domino Tile can act as a "leaf" and groups of connected tiles form "composites." This allows the system to treat individual tiles and groups of tiles uniformly, simplifying interactions such as validating moves, checking connections, and calculating scores.
For example, when a player places a tile, the board structure automatically updates to reflect its position and connection to existing tiles. The composite structure makes it easy to traverse the board and apply rules like ensuring that tile numbers match at connection points or determining whether a player can make a move. The Composite Pattern also allows for efficient score calculation by recursively aggregating the point values of connected tiles, enabling flexible rule implementation for various gameplay modes, such as doubles scoring or end-game bonus points.
This design ensures that the board's hierarchy remains consistent and simplifies complex operations like traversing tile connections or applying game-ending conditions. Extending the board's behavior, such as supporting alternative tile layouts or introducing new scoring rules, becomes straightforward, as the composite structure abstracts the complexity of hierarchical relationships.

**Comment by Keiven-Soto** [comment]
Pleade make sure to highlight you addition  in green. Great job!

**Comment by Keiven-Soto** [comment]
Thanks!
