### ISSUE TITLE
Finishing UI sounds Implementations

### ISSUE THREAD

**Issue by Joaquin939** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#408]
In this issue I'll finish implementing the UI sounds for button clicks for the rest of the pages of the project. 

Difficulty: 5
Urgency: 5

**Comment by AngelCIICMorales** [comment]
I have evaluated what the issue promises to achieve and believe this is worth around 8. If you can apply the SF to the game state buttons and the lobby buttons, I can give you 16 points. Could you also use a different sound effect for the game state, this is a personal request.

**Comment by Joaquin939** [comment]
In this task I have exceeded far and beyond the original expectations which were to add UI sounds for only the homepage buttons and at first you didn't say anything about the 20 points. And now you keep telling me to add more things while taking away more points it doesn't make sense especially when you've let me close issues where I've done far less work and got way more points. I can understand if the original points were too high and we could negotiate it but 8 points would be way too low and disrespectful towards the work I've put in to this last sprint of the project. With all the new implementations of this issue I think 15 is a fair amount of points if you so badly want to take points away. I already created the pull request.

**Comment by AngelCIICMorales** [comment]
You seem to misunderstand. What you had earlier was never worth 20 points. Other developers have done more difficult tasks that are more urgent and have been given less than 20 points. I have been trying to make your task actually be worth 20 points by making you do small improvements to it. I have received complaints from other developers and the professor for giving points away unfairly. I'm trying to be fair to every other developer who does amazing work. By giving the original task 20 points what you're saying is that adding a reused sound effect on some buttons is of equal or higher value to making the homepage itself, making the game state table, making the bots, etc. I already said I would give you 16 points, so I don't know why you ask for 15.
