### ISSUE TITLE
Add Option to View Game Instructions

### ISSUE THREAD

**Issue by Joaquin939** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#41]
As a new player to the dominoes game, I want to be able to easily access the game instructions so that I can understand the rules and how to play.

Add a button or menu option labeled "How to Play" or "Instructions" on the main menu or during gameplay.

Score:

Difficulty 4
Urgency 5

**Comment by AngelCIICMorales** [comment]
Add score.
