### ISSUE TITLE
Add derived goals to the documentation (1.5)

### ISSUE THREAD

**Issue by sandy-marrero** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#44]
> Your primary project goal is described by the other sections:
> current situation, needs, ideas, … Here you talk about secondary
> desirable outcomes. **These should be substantially different from
> your primary goals and not just reiterations of those primary
> goals.** For example, a project concerned with beach quality
> monitoring might have as its primary goal to give information about
> the cleanliness of the water and the beach to beach-goers. **A
> secondary goal could be to increase tourism to some lesser known
> beaches or to raise awareness among the public about the need to
> keep the beaches clean.**

More information at 1.5 of milestone 1 guidelines.

Temporary Score:
Urgency - 4
Difficulty - 1

**Comment by AngelCIICMorales** [comment]
I can't approve without access to the document.

**Comment by sandy-marrero** [comment]
> I can't approve without access to the document.

Fixed!

**Comment by AngelCIICMorales** [comment]
I made some suggestions. Please keep them in mind when added this to the documentation.
