### ISSUE TITLE
[UI Team] Add Multiplayer Leaderboard  Wireframe

### ISSUE THREAD

**Issue by DavidCuevas3** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#45]
### Description
This task consists of adding a wireframe for the multiplayer leaderboard with win, loss and overall global rank for multiplayer dominoes players. The leaderboard will fetch game data from the database and build a synced leaderboard. This will be implemented in tasks further on.

### Reason:
A multiplayer game benefits greatly from a leaderboard, and is essential to the players' sense of accomplishment and overall engagement.

### Current Task Objective:
Adding a multiplayer leaderboard will require multiple tasks across milestones. This issue will focus on building the wireframe, with another issue having to do with creating the visual elements (i.e. assets).

### Design Link:
https://www.figma.com/design/9tB7x524EnEF8I57CyxoMg/Colors%2C-Defaults%2C-Screens?node-id=38-2&t=eR79UJGXqdLxV5gx-1

Priority: 5
Difficulty: 3

**Comment by AngelCIICMorales** [comment]
Lgtm!
