### ISSUE TITLE
Add function signatures to the documentation (2.1.6)

### ISSUE THREAD

**Issue by sandy-marrero** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#46]
>   • For the function signatures think about what it takes to carry out
>     the action, what information will be need and what will be
>     produced/changed. For example, registering a member: Where is the
>     new member registered? In the gym? In the gym's records? In a
>     membership book? Depending on how you see this the signature would
>     have to be changed. Examples registerNewMember : Gym >< Client ->
>     Gym says that registering a client as a new member in a gym produces
>     a (likely changed) gym, registerNewMember : MembershipBook >< Client
>     -> MembershipBook reflects that the change is more local, it does
>     not pull in as many dependencies since the concept membership book
>     would be one that is accessible from gym, but other dependencies
>     from gym would be left out. registerNewMember : MembershipBook ><
>     Client -> MembershipBook >< Membership would report the newly
>     created membership as part of the result of the operation. If the
>     operation is one that can fail, you may want to provide for that
>     possibility: registerNewMember : MembershipBook >< Client ->
>     MembershipBook >< (Option Membership) where Option would be a
>     datatype wrapping a possible result or providing an indicator for
>     failure.
>   • Exercising would be a good candidate for a behavior, where a client
>     performs an exercise, then changes to a different station, …
>     possibly rests in between, …

Description according to milestone 1 guidelines section 2.1.6.

Urgency: 3
Difficulty 2

**Comment by sandy-marrero** [comment]
Latest version is ready for review:
Link: https://docs.google.com/document/d/1VRapilPMtNMFyCzaGecT4h5clO9aTjxfqZwHGstBQYA/edit?usp=sharing

Looking for feedback!

**Comment by AngelCIICMorales** [comment]
Lgtm.
