### ISSUE TITLE
Add ideas to the documentation (1.2.3)

### ISSUE THREAD

**Issue by sandy-marrero** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#47]
>   • You can include some features of the system-to-be, but refrain from
>     going too much into the requirements of the system-to-be.
>   • Do not go too much into specifics here (e.g. implementation)
>     details. Show the idea in a concise manner. Bring out the idea
>     clearly.

**Description according to milestone 1 guidelines section 1.2.3**

Urgency: 4
Difficulty: 2

**Comment by sandy-marrero** [comment]
Developed some **ideas for the documentation section** using all the project context and prior discussions, looking for feedback and sending for review.

[Google Docs Link](https://docs.google.com/document/d/1wgklMtfkXhrYNXJ-oCcmxwUzaKh95LPQn_xCdQwcyUw/edit?usp=sharing)

**Comment by AngelCIICMorales** [comment]
Thank you, it looks good; however, I don't see how this warrants 8 points. I will award 4 points. If you feel this is unfair, please let me know, and we can discuss it further.
