### ISSUE TITLE
[UI Team] Design logos for site and game

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#5]
An identifiable site and app has recognizable logos and icons. Design a title logo for the site and an icon for the site. It must be related to the overall theme of the app and follow the decided palette and aesthetic. 

Scoring:
Difficulty: 2
Urgency: 2

**Comment by PinkSylvie** [comment]
![image](https://github.com/user-attachments/assets/a24111fd-c099-47b8-81a1-fbe01dd25619)![image](https://github.com/user-attachments/assets/dcb659bf-9730-4cb5-a114-06ad8b20a6f4)

Finished the site's icon and logo and added it to the team's shared drive folder. I reached out to the person working on the mock up to get the color palette needed. Please review @AngelCIICMorales or @Keiven-Soto to close as soon as possible.

**Comment by AngelCIICMorales** [comment]
Great work!
