### ISSUE TITLE
Add Team to the documentation (1.1)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#55]
Add the team members of the project to the documentation that will be turned in.

  • Team members and partners are not 100% the same: every team member
    is a partner, but there may be partners who are not team members
    (outside experts, client, …). If you think there are no other
    partners than the team members then it might be a good idea to
    justify this. On the other hand, if you think there are possibly
    other partners who you haven't contacted yet, then it's a good idea
    to document this as well. What role and responsibilities would they
    have?
  • Customers or users are not normally partners: a partner has a higher
    stake, is more involved, in the project than a customer.

**Comment by AngelCIICMorales** [comment]
Add score.

**Comment by PinkSylvie** [comment]
Didn’t you already do this? I see the teams in the documentation. Please score the task to review and close it. @AngelCIICMorales @Keiven-Soto

**Comment by Gaby-Concepcion** [comment]
Sorry I moved it to the wrong field, though I could've sworn I had added the score last week. But yes I added the score that was discussed for these base documentation tasks and will move into the review column now.

**Comment by Keiven-Soto** [comment]
looks good
