### ISSUE TITLE
Add user stories, epics, features (2.2.1)

### ISSUE THREAD

**Issue by Gaby-Concepcion** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#57]
Include a detailed and concise account for the user stories and features to be implemented as stated ion the criteria and guidelines:

> ◊ 2.2.1 user stories, epics, features

  • Epics are like user stories, but larger. So, an epic cannot be
    implemented in a single sprint and needs to be broken into smaller
    user stories that together make up the epic. Epics can use the same
    "at a XYZ I want to ABC in order to HIJ." format. Remember it's
    important to connect the user story, epic, or feature to a more
    abstract goal that the kind of stakeholder would have.
  • Find the right granularity for the user stories. On the one hand you
    do not want them to be too broad. As in "as a student I want to get
    my enrollment done in order to have time to do more interesting
    things". In this case try zooming in and breaking them apart into
    smaller user stories. On the other hand you don't want them to be
    too detailed. As in "as a student I want to click a square button in
    order to submit my entries in the current screen". In this case take
    a step back and see what the higher-up task is to which this
    contributes. Look for meaning to the student's enrollment tasks
    themselves: does this mean anything in the context of the student
    enrolling?

Urgency: 2
Difficulty: 3

**Comment by AngelCIICMorales** [comment]
Can you please send what you have.

**Comment by Gaby-Concepcion** [comment]
Everything has been on the document since this morning, it also came back all good on my end. I don't know if you mean further revision but it should be there.

**Comment by Gaby-Concepcion** [comment]
I also apologize for the delay on tasks but I had some unexpected complications this week and it pushed me off of the project until last minute. But I hope to verify my coding implementations with the new changes so that it should be sending it in for approval and making sure they don't conflict with anything.

**Comment by Keiven-Soto** [comment]
yeah this looks good
