### ISSUE TITLE
[UI Team] Create a Mock-Up

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#60]
**Description:**

- Create a distinct mockup for the landing page of the website. This task lays the groundwork for a more concrete representation of the website's structure and layout. In case you are not familiar with mockups, I will leave a few resources and examples attached here. Use the platform of your choice, considering the suggested options or exploring alternatives.

**Deadline:**

- Aim to complete this task by September 12.

**Score:** 15 pts.

**Platform Suggestions:**

1. [Moqups](https://moqups.com/): Ideal for beginners, Moqups provides an intuitive platform for creating wireframes and mockups with ease.
2. [Figma](https://www.figma.com/): A free and versatile option for creating mockups, Figma allows collaborative design with real-time updates.
3. [UXPin](https://www.uxpin.com/): Tailored for handing off design documentation to developers, UXPin streamlines the collaboration process.
4. [Mockflow](https://www.mockflow.com/): Offering end-to-end project management, Mockflow is a comprehensive solution for mockups and design.
5. [Justinmind](https://www.justinmind.com/): Create interactive mockups with Justinmind, empowering you to visualize user experiences dynamically.
6. [Uizard](https://uizard.io/): An AI-assisted tool, Uizard accelerates the wireframing and mockup process by providing intelligent design suggestions.

**Resources:**

[Wireframing Basics (Flux Academy)](https://www.youtube.com/watch?v=HZuk6Wkx_Eg&ab_channel=FluxAcademy)
A comprehensive guide to understanding the fundamentals of wireframing. Gain insights into key concepts and best practices.
[Web Development Crash Course (freeCodeCamp.org)](https://www.youtube.com/watch?v=pN92rnO_n5U&ab_channel=freeCodeCamp.org)
A crash course in web development covering essential concepts.
[Wireframing Techniques (Flux Academy)](https://www.youtube.com/watch?v=x3Yno9VUYBY&ab_channel=FluxAcademy)
Learn how to create effective wireframes for website projects.
[Home Page Layouts (The Website Architect)](https://www.youtube.com/watch?v=g0db5kA4BfQ&ab_channel=TheWebsiteArchitect)
This tutorial caters to beginners, offering a step-by-step guide to home page layouts.
[Mockup Tutorial (freeCodeCamp.org)](https://www.youtube.com/watch?v=c9Wg6Cb_YlU&ab_channel=freeCodeCamp.org)
Guide to wireframing, mockups and website design.

**Examples:**
![Screenshot 2024-09-01 212842](https://github.com/user-attachments/assets/c0d03d98-2aab-4563-9414-3960660ead2b)

![Screenshot 2024-09-01 212914](https://github.com/user-attachments/assets/bb843173-a1df-4d78-8d44-634c9ac1fdfd)

**Comment by Adriana-Isabel** [comment]
Here's the mock-up. The logo is not the official. If there's any idea on how to make it better, please leave or comment or contact me.



![image](https://github.com/user-attachments/assets/2c5c39de-7ee7-49eb-b224-c661bb24d576)

**Comment by AngelCIICMorales** [comment]
I love how it looks, good work!
