### ISSUE TITLE
[UI Team] WebApp Header

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#62]
**Objective:**
In this task, our goal is to elevate the user experience on the home page by creating a captivating and user-friendly header. This enhancement aims to optimize navigation and search functionality.

**Subtasks:**

1. Header Creation:
- Design and implement an aesthetically pleasing header for the website.
- Ensure the header aligns with the overall theme and purpose of the website.
- Incorporate relevant features to enhance user interaction.

Deadline:
TBA

**Score:** 15 pts.

**Example:**
![Screenshot 2024-09-01 214913](https://github.com/user-attachments/assets/b0ade60a-146c-4c14-8e7e-d5e3db0aa8a7)

**Comment by AngelCIICMorales** [comment]
Add score.
