### ISSUE TITLE
[UI Team] Design assets for achievments

### ISSUE THREAD

**Issue by Saul-Caban-UPRM** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#66]
This task will focus on designing achievements assets using the website art style and this would reflect players' achievements within the game. Later on these assets would pop up on the screen showing what a player accomplished. Some examples would be First Victory: firsts players win, Winning Streaks: player's winning streaks (3,5,10.etc.), Clean Sweep:  win a round without passing, Domino Master: Accumulate a total of 20 wins, Domino Doubles: Win a round by playing the final domino as a double, etc. 

Difficulty: 4
Urgency: 4

**Comment by AngelCIICMorales** [comment]
Please provide an image in the description.

**Comment by AngelCIICMorales** [comment]
I've checked the folder everything looks good. Next time please send an image for me to review.
