### ISSUE TITLE
Develop Save System

### ISSUE THREAD

**Issue by fernandopizarro1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#70]
Implement a save system where, if the user decides to leave a game Locally, then the game is saved for later resumption. 

Priority 4
Difficulty 5

**Comment by ilikecheese117** [comment]
@fernandopizarro1

Would it be accurate to say that this is more akin to an online room that players can create and leave at any time?

**Comment by fernandopizarro1** [comment]
@ilikecheese117 Maybe we can start locally, with a player leaving a game with all bots for example, and then in the future we can apply this to an online room
