### ISSUE TITLE
Create Video Presentation of the work done in Milestone 1

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#77]
The milestone ends in Sept 20th. After the milestone ends, speak with the managers @AngelCIICMorales and @Keiven-Soto to discuss what the team accomplished this milestone to show off in the video presentation that will be shown to the professor on Sept 23rd. You'll have till Sept 22nd to submit the video but as the milestone will be over before then, your class will be closed before hand to guarantee your score for the milestone. 

This presentation will need:
- A powerpoint in which it shows what has been worked on this milestone
- A voiceover explaining the contents of the powerpoint 
-* If possible a video demo of what we currently have for the web app

**Comment by AngelCIICMorales** [comment]
Good job!
