### ISSUE TITLE
Add Machine Requirements to the documentation (2.2.5)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#78]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:

  • We want measurable requirements (whether domain requirements,
    interface requirements, or machine requirements). For example,
    "little or no" is not measurable. What could be the specific
    measurable requirement instead of "the system-to-be must have little
    or no outages"? Could the system crash? Which part? Could the system
    become slow? How slow is bearable? What should happen when more than
    X simultaneous users are there? Would the entire system be allowed
    to stop?
  • Machine requirements will need some more detail as your project
    progresses. Possibly you need to add more specific circumstances?
    What does e.g. heavily loaded even mean? Some terms here might need
    extra clarification…
  • It's OK to postpone clarification of some of these issues by saying
    e.g. "criteria for stability remain to be researched and defined",
    "acceptable degradation of services remains …"
  • Indicate that the machine requirements are still under development.
  • The machine requirements need to be measurable and attainable. For
    example, what does it mean that the platform allows 100 users? 100
    users in total registered? 100 users simultaneously accessing the
    system? Doing what? Reading a comment, running a complex query? What
    happens when we get beyond 100, say 101 users?
  • If you require very specific details of e.g. the software product
    running on the database server then you need to be able to justify
    why you think these are needed.

**Comment by Keiven-Soto** [comment]
looks good
