### ISSUE TITLE
Add Implementation to the documentation (2.3.1)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#79]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:

  • Selected fragments of the implementation are only used when they
    complement other presentations. Consider this: you are explaining
    some concepts and operations in natural language text and that
    explanation alone becomes awkward, but if you show some source code
    fragments (or diagrams, or …) along with the natural language
    explanation it becomes clear. That's where you use the fragments of
    implementation. When adding code fragments please utilize snippets
    of the actual code instead of writing it on word or using screen
    shots. By themselves diagrams and fragments of source code are not
    helpful. They are only useful if there is something that you want to
    explain/describe, the explanation is too complicated/awkward in
    natural language only, and the explanation becomes much easier to
    understand if one includes some pieces of the implementation. So,
    only when these implementation details complement your documentation
    should you include them. Never for their own sake.
  • Use quality media in your document. For example, when including
    source code, do not take a screenshot and then include the
    screenshot in the document. There are tools to properly format
    source code. Such tools are available for pretty much any software
    that you might want to use for writing. If you use markdown, for
    example, you just include a code block. On Google Docs there is
    e.g. CodeBlocks. Also, when you include a screen design use a
    scalable version of that screen design (PDF, SVG, etc.) instead of a
    raster image (JPEG, PNG, etc.).

**Comment by FrancesC8** [comment]
@JadiellMV @AngelCIICMorales I added the contents for the part _**2.3.1 Selected fragments of implementation**_ in the [documentation](https://docs.google.com/document/d/1sBqp3SlcrVe_wIFkkKQYVndjOC2MCnStxRV_ODEcgxc/edit?usp=sharing). 

Suggested points: 4

**Comment by AngelCIICMorales** [comment]
LGTM.
