### ISSUE TITLE
Add Interface Requirements to the documentation (2.2.4)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#80]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:

  • Interface requirements are about shared phenomena and concepts:
    phenomena and concepts that can be observed in the domain and that
    are relevant to the simulation of part of the domain in the
    system-to-be and how they are shared between the domain and the
    internal representation inside the system. For example, in a project
    revolving around cooking, recipes, ingredients, and learning
    different dishes how often I have prepared a given dish is a concept
    from the domain and let's assume you have decided that it is
    relevant to the requirements of your application and so must be
    represented inside the system-to-be. How is value in the
    system-to-be initialized? From which observation in the domain? How
    is it updated when a dish is actually prepared in the outside world?
    Is there a connection to the cook's kitchen, to their stove, or does
    the system-to-be provide a screen in which the cook clicks a
    "Prepared" button to increase the number?  These are all interface
    considerations and your choices are captured as interface
    requirements.
  • Example, there are artworks that exist outside the system in the
    domain. We have decided that these need to be represented inside the
    system. By what means does the system go from not having any
    artworks within it to having representations of those artworks? We
    need to state requirements that characterize the initialization of
    the artworks in the system. We also need to characterize means to
    update the representation inside the system should the
    characteristics of an artworks in the domain change.
  • There are many more interface requirements: can information about
    outside phenomena and concepts that was incorrectly or incompletely
    entered be updated? Can such information be edited? Can it be
    changed? In which ways? Which information should not be changed once
    it was entered?
  • For example, a student drops a course that they had enrolled
    into. This is an occurrence we can observe in the domain. In order
    for the system-to-be to reflect this information correctly, it needs
    to be entered/edited in the system. How? When?
  • Some requirements that appear to be interface requirements can
    actually be decomposed into several parts. Some parts are concerned
    with the interface aspects and others e.g. with the domain
    aspects. That the system provides mean to the user to create an
    assignment is not purely an interface requirement. There is an
    interface requirement part to this, but there are also non-interface
    related requirements e.g. that assignments (internal representation)
    need to be created on behalf of the user.
  • Many of your interface requirements can be derived by looking at the
    domain requirements, seeing that they require some concepts from the
    domain to be represented inside the system-to-be and then asking
    yourself: "hoe is that internal data representation first obtained?
    How is it kept up-to-date when the phenomenon in the domain
    changes?"

**Comment by AngelCIICMorales** [comment]
LGTM.
