### ISSUE TITLE
Add Events, Actions, and Behaviors to the documentation (2.1.5)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#82]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:

  • There is a difference between the moment from which a person has
    just become a member (event), the act of becoming a member (action),
    and the process consisting of various smaller actions that together
    make up the "becoming a member" (behavior).

**Comment by Keiven-Soto** [comment]
looks good
