### ISSUE TITLE
Add Terminology in relation to Domain Rough Sketch documentation (2.1.3)

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#91]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:
Guidelines:
- [ ] The domain terminology is not part of the rough sketch: to develop the terminology you have to analyze the rough sketch and come up with good definitions for the terms used e.g. in stakeholder interviews. So, the definitions are results of the processing and are therefore not rough.

**Comment by AngelCIICMorales** [comment]
LGTM
