### ISSUE TITLE
Add Narrative to documentation (2.1.4)

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#92]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:

Guidelines:

- [ ] The domain narrative tells the story of the domain. The domain is that part of the universe of interest to your project but independent of the system-to-be. So, "When a student enrolls into a course, the student has this course for the running semester unless the student drops the course." could be part of the domain narrative, but anything talking about the "application" is not part of domain narrative.
- [ ] The domain is that part of the universe that is of interest to your project, but independent of any system-to-be. Therefore, "home page", "navigation bar" etc. have no place here. You can describe these where you start talking about the actual implementation. Also, in domain narrative you want to talk about the _domain_ not about using the application.
- [ ] Narrative: Again, you're talking about the app that you will create, not the domain. The narrative is supposed to tell you how the domain currently works without your project and is a more elaborate version of your sketch.
- [ ] The first paragraph of the domain narrative talks about the necessity to understand but not about the domain itself. It's valuable, but should be placed somewhere else.
- [ ] The domain narrative is similarly not concerned with the platform, application, or system-to-be. You start with the creation of an event in the application that will notify all users that the creator of said event selects. Then the third paragraph talks about how the team plans to implement this. Implementation is also not part of the domain.
- [ ] You cannot "add an artist to the domain". The domain is the part of the observable universe that is relevant to your project but independent of the system-to-be. In your case you can observe that there are artists. You observe this in the world, but you do not add an artist to the domain. You can add an artist to the system-to-be, but that is not a domain function since it assumes the existence of the system-to-be and so is not independent of that system-to-be. Something that can be done in the domain to the artist: observe/obtain their name, or observe their art. Similarly, we can assume that for some given work of art there is a way to obtain the artist who created it. That would be a function in the domain. We could call the function "obtainCreator : ArtWork -> Artist", but then we might decide that there may be works of art that have several creators and instead we would write "obtainCreator : ArtWork -> Set Artist". If we would want to exclude the possibility that a work of art has no creator, we could even write "obtainCreator : ArtWork -> NonEmptySet Artist". The entities you have are all from the domain, but some functionality and events that you have identified are not from the domain. Which related functionality or event exists in the domain independent of a system-to-be?
- [ ] Similarly for domain entities: "register to the application" is not within the domain. Keeping track of sessions and allowing users to continue from past sessions is an application concern: only because you want to simulate part of the domain in the system-to-be do you need sessions, registration in the application, login, … Go over all domain entities with this in mind.
- [ ] Narrative - The domain is that part of the observed universe that is related to the project but independent of the system-to-be (which cannot yet be observed). In the context of car histories we have the phenomena and concepts of cars, owners, transfer of ownership, maintenance, repair, … These are all independent of the system-to-be. The domain description is then a documentation of that domain in a way that is suitable for further development (requirements, architecture, implementation, …).
- [ ]

**Comment by AngelCIICMorales** [comment]
LGTM
