### ISSUE TITLE
Add Domain Description to the documentation (2.1)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes#95]
Add the information needed to section mentioned above following the explanation provided by the professor below and the examples shared in moodle and the discussion, make sure to bring to the professor beforehand for review:

  • Functions stand for actions, operations, things that can be done to
    or with the entities. For example, an appointment can be "made", or
    "canceled", or "attended". What is required when we would make an
    appointment? For who the appointment is made, for how long. What is
    the result of making an appointment? Well, an appointment. So, we
    might capture this first approach to understanding in
    "makeAppointment(forWho:Patient, when:Period) : Appointment". But
    then we might consider how to think about conflicting appointments
    (slots already taken). From what I just wrote there is no way to
    check since the function would not have access to a calendar. So, we
    might consider passing in a calendar, but that would bring in all of
    the concepts related to the calendar. Instead we might drill it down
    to only the bare minimum in concepts: we need to know the available
    periods. Then "makeAppointment(forWho:Patient, when:Period,
    free:List Period) : Appointment". Still we need to think about
    dealing with the possibility that an appointment can not be
    allocated if no slot long enough is
    available. "makeAppointment(forWho:Patient, when:Period, free:List
    Period) : Option Appointment" where "Option a" indicates either
    "Success" with a value of type 'a' or "Failure".
  • When thinking about domain functions I recommend looking at them as
    first-class citizens. i.e. not as functions that belong to a single
    entity.
  • Beware that the structures you define are suitable in general. For
    example, when describing a game as a domain entity: does every game
    use rounds? So should rounds be something you can observe on every
    game?
  • Ensure that the functions, events, or behaviors are really from the
    domain. Think about the operations in the domain very thoroughly:
    for example, when you "add an event" what all do you need? What are
    you adding? An event. Where are you adding it to? A schedule?  What
    are you getting as a result? A modified schedule?
  • Look over the domain functions, domain events, domain behaviors and
    see whether they are really from the domain: i.e. are they purely
    introduced by the need of describing the domain independently of the
    application.
  • We have the domain description which only explains the phenomena and
    concepts from the domain. "Calendar", "appointment", … would be
    concepts to go there in a project concerned with e.g. doctor's
    appointments. The domain is independent of any system-to-be. Then we
    have the requirements that capture what a system-to-be would have to
    "do". One way to capture the requirements is as user
    stories. Typically, user stories would make use of some concepts
    from the domain, but might speak of additional concepts that come
    e.g. from the need to implement this as a system. For
    example. "session".
  • The domain description (rough sketch, terminology, narrative, …) is
    concerned only with those concepts and phenomena that can be
    observed in the domain independently of the system-to-be. So, be
    careful referring to a system in any of the descriptions of the
    domain. When you describe (or prescribe) the requirements you start
    talking about behaviors that the system must have.
  • Domain description, etc. are not added to your web
    application. These are activities or outcomes of activities that are
    needed to have a well-founded project.

**Comment by frances-sepulveda** [comment]
The Domain description has been finished in the documentation.

**Comment by Keiven-Soto** [comment]
Please revise your documentation task specially this one paragraph

"The game of dominoes, especially in its multiplayer online form, is a testament to the enduring appeal of traditional games in modern society. It serves as a reminder that even in an increasingly digital world, the basic human need for connection, competition, and collaboration remains unchanged. Whether played at a family gathering in Puerto Rico or through an online platform connecting players from around the globe, dominoes continues to thrive as a game that brings people together, fosters strategic thinking, and provides hours of entertainment." 

It sounds redundant

**Comment by frances-sepulveda** [comment]
it was changed a bit ago, please revised again. Thank you!

**Comment by PinkSylvie** [comment]
![Image](https://github.com/user-attachments/assets/2af4c15b-1887-4a2c-aeaa-0c167ba3a9aa)
• We have the domain description which only explains the phenomena and
concepts from the domain. "Calendar", "appointment", … would be
concepts to go there in a project concerned with e.g. doctor's
appointments. The domain is independent of any system-to-be. Then we
have the requirements that capture what a system-to-be would have to
"do". One way to capture the requirements is as user
stories. Typically, user stories would make use of some concepts
from the domain, but might speak of additional concepts that come
e.g. from the need to implement this as a system. For
example. "session".
• The domain description (rough sketch, terminology, narrative, …) is
concerned only with those concepts and phenomena that can be
observed in the domain independently of the system-to-be. So, be
careful referring to a system in any of the descriptions of the
domain. When you describe (or prescribe) the requirements you start
talking about behaviors that the system must have.
• Domain description, etc. are not added to your web
application. These are activities or outcomes of activities that are
needed to have a well-founded project.

I'm concerned about this as what you wrote clearly talks about the system to be which would be the app. Clearly the instructions refer to not doing so and describing the environment actions and phenomena and actions of dominoes that would inspire us to do the things that will do for the app

**Comment by frances-sepulveda** [comment]
It was changed. Please review it. Thank you!

**Comment by PinkSylvie** [comment]
Was just reading it and wondering what changed? I still see the same references to the system to be that the instructions mentioned that shouldn't be included on the description.

**Comment by frances-sepulveda** [comment]
The final changes were done and it was approved by @PinkSylvie. Please review it, thank you!

**Comment by AngelCIICMorales** [comment]
I have reduced the task to 8 points because that was the maximum amount of points a documentation task could have.
